theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
auto-save = true
bufferline = "multiple"

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = [
  "version-control",
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "🤔"
mode.insert = "🫣"
mode.select = "🤏"

[keys.normal]
# Escape selections as expected
esc = ["collapse_selection", "keep_primary_selection"]
# Return to save all
ret = ":wa"
# Use the system clipboard like a normal app
d = ["yank_joined_to_clipboard", "delete_selection_noyank"]
D = "delete_selection_noyank"
y = "yank_joined_to_clipboard"
Y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"

# I use an arrow keys layer so i can remap hjkl
j = "join_selections"

# Search for word under cursor
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_next",
]
# Control-Arrows to switch panes
C-up = "jump_view_up"
C-down = "jump_view_down"
C-left = "jump_view_left"
C-right = "jump_view_right"
# Shift Arrows move 5 times in direction
S-up = [
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
]
S-down = [
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
]
S-left = [
  "move_char_left",
  "move_char_left",
  "move_char_left",
  "move_char_left",
  "move_char_left",
]
S-right = [
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

# Use the system clipboard like a normal app
d = ["yank_joined_to_clipboard", "delete_selection_noyank"]
D = "delete_selection_noyank"
y = "yank_joined_to_clipboard"
p = "replace_selections_with_clipboard"

[keys.normal.space]
# Git shell
l = [":sh lazygit", ":reload-all"]
# Semi-permenant scratch file
c = ":o /tmp/scratch"
# Poor mans magit
t = [
  ":o /tmp/gitstatus",
  "select_all",
  "delete_selection_noyank",
  ":insert-output git status -s",
  "collapse_selection",
  "goto_file_start",
  "move_char_right",
  "move_char_right",
  "move_char_right",
]
