{ pkgs, ... }: {
  home.packages = with pkgs; [
    aws-google-auth
    awscli2
    bat
    cheat
    circleci-cli
    deno
    dig
    direnv
    dive
    docker-compose
    eksctl
    exa
    firefox-devedition-bin
    fzf
    ghc
    gnuplot
    go
    gopls
    graphviz
    haskellPackages.haskell-language-server
    hledger
    htop
    jq
    kubectl
    neofetch
    nixfmt
    nixpkgs-fmt
    nodePackages.bash-language-server
    nodePackages.dockerfile-language-server-nodejs
    nodePackages.javascript-typescript-langserver
    nodePackages.typescript
    nodejs
    openvpn
    pandoc
    python
    python3
    ripgrep
    rnix-lsp
    rustup
    sqlite
    stack
    terraform_0_15
    tldr
    vim
    yarn
  ];
}
