modkey = "Mod4"
mousekey = "Mod4"
workspaces = [ ]
tags = ["1", "2", "3", "4"]
layouts = ["Monocle", "MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "RightWiderLeftStack", "LeftWiderRightStack"]
scratchpad = []
disable_current_tag_swap = false
focus_behaviour = "Sloppy"
focus_new_windows = true

[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "SoftReload"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "Execute"
value = "lock-screen"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "t"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "r"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey"]
key = "m"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "f"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "s"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "s"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Shift"]
key = "t"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey", "Shift", "Control"]
key = "t"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey", "Shift", "Control"]
key = "r"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "z"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "x"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "c"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "z"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "c"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "d"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "g"
