matches:
  # Dates
  - trigger: ".,da"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ".,dd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ".,dh"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "# %d %a"
  - trigger: ".,tt"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  # Shell commands
  - trigger: ".,ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.co"

  # Vim
  - trigger: ".,."
    replace: "\\(.*\\)"

  # Personal
  - trigger: ".,eg"
    replace: "danelipscombe@gmail.com"
  - trigger: ".,ew"
    replace: "dane.lipscombe@playtravel.com.au"
  - trigger: ",.n"
    replace: "Dane Lipscombe"
  - trigger: ".,f"
    replace: "Dane"
  - trigger: ".,l"
    replace: "Lipscombe"
  - trigger: ".,p"
    replace: "TestPassword!123"
  - trigger: ".,c"
    replace: "42424242424242420125123"
