matches:
  # Dates
  - trigger: "dasx,;"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: "dadx,;"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "damx,;"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "# %d %a"
  - trigger: "tix,;"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  # Shell commands
  - trigger: "ipx,;"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.co"

  # Vim
  - trigger: "vx,;"
    replace: "\\(.*\\)"
  # Personal
  - trigger: "egx,;"
    replace: "danelipscombe@gmail.com"
  - trigger: "ewx,;"
    replace: "dane.lipscombe@planpay.com"
  - trigger: "dlx,;"
    replace: "Dane Lipscombe"
  - trigger: "dx,;"
    replace: "Dane"
  - trigger: "lx,;"
    replace: "Lipscombe"
  - trigger: "tpx,;"
    replace: "TestPassword!123"
  - trigger: "tcx,;"
    replace: "42424242424242420125123"
