matches:
  # Dates
  - trigger: ".,da"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ".,dd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ".,dh"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "# %d %a"
  - trigger: ".,tt"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  # Shell commands
  - trigger: ".,ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.co"

  # Vim
  - trigger: "..,"
    replace: "\\(.*\\)"

  # Personal
  - trigger: "@.,"
    replace: "danelipscombe@gmail.com"
  - trigger: "@p.,"
    replace: "dlip1@protonmail.com"
  - trigger: "@w.,"
    replace: "dane.lipscombe@playtravel.com.au"
  - trigger: "dl.,"
    replace: "Dane Lipscombe"
  - trigger: "zD.,"
    replace: "Dane"
  - trigger: "zL.,"
    replace: "Lipscombe"

