matches:
  # Dates
  - trigger: "das',;"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: "dad',;"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "dam',;"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "# %d %a"
  - trigger: "ti',;"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  # Shell commands
  - trigger: "ip',;"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.co"

  # Vim
  - trigger: "v',;"
    replace: "\\(.*\\)"
  # Personal
  - trigger: "eg',;"
    replace: "danelipscombe@gmail.com"
  - trigger: "ew',;"
    replace: "dane.lipscombe@planpay.com"
  - trigger: "dl',;"
    replace: "Dane Lipscombe"
  - trigger: "d',;"
    replace: "Dane"
  - trigger: "l',;"
    replace: "Lipscombe"
  - trigger: "tp',;"
    replace: "TestPassword!123"
  - trigger: "tc',;"
    replace: "42424242424242420125123"
