matches:
  # Dates
  - trigger: ".,da"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ".,dd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ".,dh"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "# %d %a"
  - trigger: ".,tt"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  # Shell commands
  - trigger: ".,ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.co"

  # Vim
  - trigger: "..,"
    replace: "\\(.*\\)"

  # Personal
  - trigger: "@.,"
    replace: "danelipscombe@gmail.com"
  - trigger: "@p.,"
    replace: "dlip1@protonmail.com"
  - trigger: "@w.,"
    replace: "dane.lipscombe@playtravel.com.au"
  - trigger: "dl.,"
    replace: "Dane Lipscombe"
  - trigger: "zD.,"
    replace: "Dane"
  - trigger: "zL.,"
    replace: "Lipscombe"

  # BRIEFS START
  - trigger: "i"
    replace: "I"
    word: true
  - trigger: "I"
    replace: "I"
    word: true
  - trigger: "il"
    replace: "I'll"
    word: true
    propagate_case: true
  - trigger: "t"
    replace: "the"
    word: true
  - trigger: "T"
    replace: "The"
    word: true
  - trigger: "x"
    replace: "and"
    word: true
  - trigger: "X"
    replace: "And"
    word: true
  - trigger: "its"
    replace: "it's"
    word: true
    propagate_case: true
  - trigger: "u"
    replace: "you"
    word: true
  - trigger: "U"
    replace: "You"
    word: true
  - trigger: "th"
    replace: "that"
    word: true
    propagate_case: true
  - trigger: "ths"
    replace: "that's"
    word: true
    propagate_case: true
  - trigger: "z"
    replace: "was"
    word: true
  - trigger: "Z"
    replace: "Was"
    word: true
  - trigger: "f"
    replace: "for"
    word: true
  - trigger: "F"
    replace: "For"
    word: true
  - trigger: "ar"
    replace: "are"
    word: true
    propagate_case: true
  - trigger: "w"
    replace: "with"
    word: true
  - trigger: "W"
    replace: "With"
    word: true
  - trigger: "h"
    replace: "his"
    word: true
  - trigger: "H"
    replace: "His"
    word: true
  - trigger: "ty"
    replace: "they"
    word: true
    propagate_case: true
  - trigger: "o"
    replace: "one"
    word: true
  - trigger: "O"
    replace: "One"
    word: true
  - trigger: "ha"
    replace: "have"
    word: true
    propagate_case: true
  - trigger: "thi"
    replace: "this"
    word: true
    propagate_case: true
  - trigger: "fm"
    replace: "from"
    word: true
    propagate_case: true
  - trigger: "hd"
    replace: "had"
    word: true
    propagate_case: true
  - trigger: "ho"
    replace: "hot"
    word: true
    propagate_case: true
  - trigger: "b"
    replace: "but"
    word: true
  - trigger: "B"
    replace: "But"
    word: true
  - trigger: "s"
    replace: "some"
    word: true
  - trigger: "S"
    replace: "Some"
    word: true
  - trigger: "wh"
    replace: "what"
    word: true
    propagate_case: true
  - trigger: "thr"
    replace: "there"
    word: true
    propagate_case: true
  - trigger: "c"
    replace: "can"
    word: true
  - trigger: "C"
    replace: "Can"
    word: true
  - trigger: "ou"
    replace: "out"
    word: true
    propagate_case: true
  - trigger: "ot"
    replace: "other"
    word: true
    propagate_case: true
  - trigger: "wr"
    replace: "were"
    word: true
    propagate_case: true
  - trigger: "al"
    replace: "all"
    word: true
    propagate_case: true
  - trigger: "yr"
    replace: "your"
    word: true
    propagate_case: true
  - trigger: "whe"
    replace: "when"
    word: true
    propagate_case: true
  - trigger: "ys"
    replace: "use"
    word: true
    propagate_case: true
  - trigger: "wo"
    replace: "word"
    word: true
    propagate_case: true
  - trigger: "hw"
    replace: "how"
    word: true
    propagate_case: true
  - trigger: "sa"
    replace: "said"
    word: true
    propagate_case: true
  - trigger: "e"
    replace: "each"
    word: true
  - trigger: "E"
    replace: "Each"
    word: true
  - trigger: "sh"
    replace: "she"
    word: true
    propagate_case: true
  - trigger: "whi"
    replace: "which"
    word: true
    propagate_case: true
  - trigger: "thei"
    replace: "their"
    word: true
    propagate_case: true
  - trigger: "ti"
    replace: "time"
    word: true
    propagate_case: true
  - trigger: "wi"
    replace: "will"
    word: true
    propagate_case: true
  - trigger: "wa"
    replace: "way"
    word: true
    propagate_case: true
  - trigger: "ab"
    replace: "about"
    word: true
    propagate_case: true
  - trigger: "m"
    replace: "many"
    word: true
  - trigger: "M"
    replace: "Many"
    word: true
  - trigger: "thn"
    replace: "then"
    word: true
    propagate_case: true
  - trigger: "thm"
    replace: "them"
    word: true
    propagate_case: true
  - trigger: "wl"
    replace: "would"
    word: true
    propagate_case: true
  - trigger: "wri"
    replace: "write"
    word: true
    propagate_case: true
  - trigger: "l"
    replace: "like"
    word: true
  - trigger: "L"
    replace: "Like"
    word: true
  - trigger: "thes"
    replace: "these"
    word: true
    propagate_case: true
  - trigger: "hr"
    replace: "her"
    word: true
    propagate_case: true
  - trigger: "lo"
    replace: "long"
    word: true
    propagate_case: true
  - trigger: "mk"
    replace: "make"
    word: true
    propagate_case: true
  - trigger: "thin"
    replace: "thing"
    word: true
    propagate_case: true
  - trigger: "se"
    replace: "see"
    word: true
    propagate_case: true
  - trigger: "hi"
    replace: "him"
    word: true
    propagate_case: true
  - trigger: "tw"
    replace: "two"
    word: true
    propagate_case: true
  - trigger: "hs"
    replace: "has"
    word: true
    propagate_case: true
  - trigger: "lk"
    replace: "look"
    word: true
    propagate_case: true
  - trigger: "mo"
    replace: "more"
    word: true
    propagate_case: true
  - trigger: "d"
    replace: "day"
    word: true
  - trigger: "D"
    replace: "Day"
    word: true
  - trigger: "co"
    replace: "could"
    word: true
    propagate_case: true
  - trigger: "cm"
    replace: "come"
    word: true
    propagate_case: true
  - trigger: "di"
    replace: "did"
    word: true
    propagate_case: true
  - trigger: "snd"
    replace: "sound"
    word: true
    propagate_case: true
  - trigger: "ms"
    replace: "most"
    word: true
    propagate_case: true
  - trigger: "n"
    replace: "number"
    word: true
  - trigger: "N"
    replace: "Number"
    word: true
  - trigger: "hu"
    replace: "who"
    word: true
    propagate_case: true
  - trigger: "ov"
    replace: "over"
    word: true
    propagate_case: true
  - trigger: "k"
    replace: "know"
    word: true
  - trigger: "K"
    replace: "Know"
    word: true
  - trigger: "wt"
    replace: "water"
    word: true
    propagate_case: true
  - trigger: "tha"
    replace: "than"
    word: true
    propagate_case: true
  - trigger: "ca"
    replace: "call"
    word: true
    propagate_case: true
  - trigger: "fi"
    replace: "first"
    word: true
    propagate_case: true
  - trigger: "p"
    replace: "people"
    word: true
  - trigger: "P"
    replace: "People"
    word: true
  - trigger: "mi"
    replace: "may"
    word: true
    propagate_case: true
  - trigger: "dw"
    replace: "down"
    word: true
    propagate_case: true
  - trigger: "si"
    replace: "side"
    word: true
    propagate_case: true
  - trigger: "bn"
    replace: "been"
    word: true
    propagate_case: true
  - trigger: "nw"
    replace: "now"
    word: true
    propagate_case: true
  - trigger: "fn"
    replace: "find"
    word: true
    propagate_case: true
  - trigger: "ne"
    replace: "any"
    word: true
    propagate_case: true
  - trigger: "nu"
    replace: "new"
    word: true
    propagate_case: true
  - trigger: "wor"
    replace: "work"
    word: true
    propagate_case: true
  - trigger: "pa"
    replace: "part"
    word: true
    propagate_case: true
  - trigger: "ta"
    replace: "take"
    word: true
    propagate_case: true
  - trigger: "g"
    replace: "get"
    word: true
  - trigger: "G"
    replace: "Get"
    word: true
  - trigger: "pl"
    replace: "place"
    word: true
    propagate_case: true
  - trigger: "md"
    replace: "made"
    word: true
    propagate_case: true
  - trigger: "li"
    replace: "live"
    word: true
    propagate_case: true
  - trigger: "whr"
    replace: "where"
    word: true
    propagate_case: true
  - trigger: "af"
    replace: "after"
    word: true
    propagate_case: true
  - trigger: "ba"
    replace: "back"
    word: true
    propagate_case: true
  - trigger: "ltl"
    replace: "little"
    word: true
    propagate_case: true
  - trigger: "onl"
    replace: "only"
    word: true
    propagate_case: true
  - trigger: "r"
    replace: "round"
    word: true
  - trigger: "R"
    replace: "Round"
    word: true
  - trigger: "ma"
    replace: "man"
    word: true
    propagate_case: true
  - trigger: "ya"
    replace: "year"
    word: true
    propagate_case: true
  - trigger: "cam"
    replace: "came"
    word: true
    propagate_case: true
  - trigger: "sho"
    replace: "show"
    word: true
    propagate_case: true
  - trigger: "ev"
    replace: "every"
    word: true
    propagate_case: true
  - trigger: "gd"
    replace: "good"
    word: true
    propagate_case: true
  - trigger: "gi"
    replace: "give"
    word: true
    propagate_case: true
  - trigger: "oa"
    replace: "our"
    word: true
    propagate_case: true
  - trigger: "un"
    replace: "under"
    word: true
    propagate_case: true
  - trigger: "na"
    replace: "name"
    word: true
    propagate_case: true
  - trigger: "v"
    replace: "very"
    word: true
  - trigger: "V"
    replace: "Very"
    word: true
  - trigger: "thro"
    replace: "through"
    word: true
    propagate_case: true
  - trigger: "j"
    replace: "just"
    word: true
  - trigger: "J"
    replace: "Just"
    word: true
  - trigger: "fo"
    replace: "form"
    word: true
    propagate_case: true
  - trigger: "mu"
    replace: "much"
    word: true
    propagate_case: true
  - trigger: "gr"
    replace: "great"
    word: true
    propagate_case: true
  - trigger: "tk"
    replace: "think"
    word: true
    propagate_case: true
  - trigger: "sy"
    replace: "say"
    word: true
    propagate_case: true
  - trigger: "hl"
    replace: "help"
    word: true
    propagate_case: true
  - trigger: "lw"
    replace: "low"
    word: true
    propagate_case: true
  - trigger: "ln"
    replace: "line"
    word: true
    propagate_case: true
  - trigger: "bf"
    replace: "before"
    word: true
    propagate_case: true
  - trigger: "tn"
    replace: "turn"
    word: true
    propagate_case: true
  - trigger: "cs"
    replace: "cause"
    word: true
    propagate_case: true
  - trigger: "sm"
    replace: "same"
    word: true
    propagate_case: true
  - trigger: "mea"
    replace: "mean"
    word: true
    propagate_case: true
  - trigger: "df"
    replace: "differ"
    word: true
    propagate_case: true
  - trigger: "mv"
    replace: "move"
    word: true
    propagate_case: true
  - trigger: "ri"
    replace: "right"
    word: true
    propagate_case: true
  - trigger: "bo"
    replace: "boy"
    word: true
    propagate_case: true
  - trigger: "ol"
    replace: "old"
    word: true
    propagate_case: true
  - trigger: "tu"
    replace: "too"
    word: true
    propagate_case: true
  - trigger: "ds"
    replace: "does"
    word: true
    propagate_case: true
  - trigger: "te"
    replace: "tell"
    word: true
    propagate_case: true
  - trigger: "snt"
    replace: "sentence"
    word: true
    propagate_case: true
  - trigger: "st"
    replace: "set"
    word: true
    propagate_case: true
  - trigger: "thre"
    replace: "three"
    word: true
    propagate_case: true
  - trigger: "wn"
    replace: "want"
    word: true
    propagate_case: true
  - trigger: "ai"
    replace: "air"
    word: true
    propagate_case: true
  - trigger: "wel"
    replace: "well"
    word: true
    propagate_case: true
  - trigger: "als"
    replace: "also"
    word: true
    propagate_case: true
  - trigger: "pla"
    replace: "play"
    word: true
    propagate_case: true
  - trigger: "sma"
    replace: "small"
    word: true
    propagate_case: true
  - trigger: "en"
    replace: "end"
    word: true
    propagate_case: true
  - trigger: "pu"
    replace: "put"
    word: true
    propagate_case: true
  - trigger: "hm"
    replace: "home"
    word: true
    propagate_case: true
  - trigger: "re"
    replace: "read"
    word: true
    propagate_case: true
  - trigger: "hn"
    replace: "hand"
    word: true
    propagate_case: true
  - trigger: "po"
    replace: "port"
    word: true
    propagate_case: true
  - trigger: "la"
    replace: "large"
    word: true
    propagate_case: true
  - trigger: "sp"
    replace: "spell"
    word: true
    propagate_case: true
  - trigger: "ad"
    replace: "add"
    word: true
    propagate_case: true
  - trigger: "eve"
    replace: "even"
    word: true
    propagate_case: true
  - trigger: "lan"
    replace: "land"
    word: true
    propagate_case: true
  - trigger: "her"
    replace: "here"
    word: true
    propagate_case: true
  - trigger: "mus"
    replace: "must"
    word: true
    propagate_case: true
  - trigger: "bi"
    replace: "big"
    word: true
    propagate_case: true
  - trigger: "hg"
    replace: "high"
    word: true
    propagate_case: true
  - trigger: "su"
    replace: "such"
    word: true
    propagate_case: true
  - trigger: "fl"
    replace: "follow"
    word: true
    propagate_case: true
  - trigger: "ac"
    replace: "act"
    word: true
    propagate_case: true
  - trigger: "y"
    replace: "why"
    word: true
  - trigger: "Y"
    replace: "Why"
    word: true
  - trigger: "ak"
    replace: "ask"
    word: true
    propagate_case: true
  - trigger: "mn"
    replace: "men"
    word: true
    propagate_case: true
  - trigger: "ch"
    replace: "change"
    word: true
    propagate_case: true
  - trigger: "wen"
    replace: "went"
    word: true
    propagate_case: true
  - trigger: "lt"
    replace: "light"
    word: true
    propagate_case: true
  - trigger: "ki"
    replace: "kind"
    word: true
    propagate_case: true
  - trigger: "ff"
    replace: "off"
    word: true
    propagate_case: true
  - trigger: "nd"
    replace: "need"
    word: true
    propagate_case: true
  - trigger: "hou"
    replace: "house"
    word: true
    propagate_case: true
  - trigger: "pi"
    replace: "picture"
    word: true
    propagate_case: true
  - trigger: "tr"
    replace: "try"
    word: true
    propagate_case: true
  - trigger: "ag"
    replace: "again"
    word: true
    propagate_case: true
  - trigger: "ani"
    replace: "animal"
    word: true
    propagate_case: true
  - trigger: "pn"
    replace: "point"
    word: true
    propagate_case: true
  - trigger: "mt"
    replace: "mother"
    word: true
    propagate_case: true
  - trigger: "wrl"
    replace: "world"
    word: true
    propagate_case: true
  - trigger: "nr"
    replace: "near"
    word: true
    propagate_case: true
  - trigger: "bu"
    replace: "build"
    word: true
    propagate_case: true
  - trigger: "sl"
    replace: "self"
    word: true
    propagate_case: true
  - trigger: "ea"
    replace: "earth"
    word: true
    propagate_case: true
  - trigger: "ftr"
    replace: "father"
    word: true
    propagate_case: true
  - trigger: "hea"
    replace: "head"
    word: true
    propagate_case: true
  - trigger: "sta"
    replace: "stand"
    word: true
    propagate_case: true
  - trigger: "ow"
    replace: "own"
    word: true
    propagate_case: true
  - trigger: "pg"
    replace: "page"
    word: true
    propagate_case: true
  - trigger: "shl"
    replace: "should"
    word: true
    propagate_case: true
  - trigger: "cn"
    replace: "country"
    word: true
    propagate_case: true
  - trigger: "fou"
    replace: "found"
    word: true
    propagate_case: true
  - trigger: "ans"
    replace: "answer"
    word: true
    propagate_case: true
  - trigger: "sc"
    replace: "school"
    word: true
    propagate_case: true
  - trigger: "gro"
    replace: "grow"
    word: true
    propagate_case: true
  - trigger: "stu"
    replace: "study"
    word: true
    propagate_case: true
  - trigger: "sti"
    replace: "still"
    word: true
    propagate_case: true
  - trigger: "le"
    replace: "learn"
    word: true
    propagate_case: true
  - trigger: "pln"
    replace: "plant"
    word: true
    propagate_case: true
  - trigger: "cv"
    replace: "cover"
    word: true
    propagate_case: true
  - trigger: "fd"
    replace: "food"
    word: true
    propagate_case: true
  - trigger: "sn"
    replace: "sun"
    word: true
    propagate_case: true
  - trigger: "fr"
    replace: "four"
    word: true
    propagate_case: true
  - trigger: "tho"
    replace: "thought"
    word: true
    propagate_case: true

  # BRIEFS END
