matches:
  # Dates
  - trigger: ".,da"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ".,dd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ".,dh"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "# %d %a"
  - trigger: ".,tt"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  # Shell commands
  - trigger: ".,ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.co"

  # Vim
  # - trigger: ".,."
  #   replace: "\\(.*\\)"

  # Personal
  - trigger: "emg,;"
    replace: "danelipscombe@gmail.com"
  - trigger: "emw,;"
    replace: "dane.lipscombe@planpay.com"
  - trigger: "dl,;"
    replace: "Dane Lipscombe"
  - trigger: "dn,;"
    replace: "Dane"
  - trigger: "lp,;"
    replace: "Lipscombe"
  - trigger: "tp,;"
    replace: "TestPassword!123"
  - trigger: "tc,;"
    replace: "42424242424242420125123"
