matches:
 - trigger: "th.,"
   replace: "the "
 - trigger: "nd.,"
   replace: "and "
 - trigger: "u.,"
   replace: "you "
 - trigger: "fr.,"
   replace: "for "
 - trigger: "ws.,"
   replace: "was "
 - trigger: "r.,"
   replace: "are "
 - trigger: "tht.,"
   replace: "that "
 - trigger: "wth.,"
   replace: "with "
 - trigger: "ty.,"
   replace: "they "
 - trigger: "hv.,"
   replace: "have "
 - trigger: "ths.,"
   replace: "this "
 - trigger: "frm.,"
   replace: "from "
 - trigger: "hd.,"
   replace: "had "
 - trigger: "nt.,"
   replace: "not "
 - trigger: "bt.,"
   replace: "but "
 - trigger: "wt.,"
   replace: "what "
 - trigger: "cn.,"
   replace: "can "
 - trigger: "al.,"
   replace: "all "
 - trigger: "thr.,"
   replace: "their "
 - trigger: "thr.,"
   replace: "there "
 - trigger: "wch.,"
   replace: "which "
 - trigger: "wn.,"
   replace: "when "
 - trigger: "1.,"
   replace: "one "
 - trigger: "wld.,"
   replace: "would "
 - trigger: "bn.,"
   replace: "been "
 - trigger: "wh.,"
   replace: "who "
 - trigger: "wl.,"
   replace: "will "
 - trigger: "thm.,"
   replace: "them "
 - trigger: "sm.,"
   replace: "some "
 - trigger: "hw.,"
   replace: "how "
 - trigger: "othr.,"
   replace: "other "
 - trigger: "cld.,"
   replace: "could "
 - trigger: "int.,"
   replace: "into "
 - trigger: "thn.,"
   replace: "than "
 - trigger: "thn.,"
   replace: "then "
 - trigger: "nw.,"
   replace: "now "
 - trigger: "lk.,"
   replace: "like "
 - trigger: "yr.,"
   replace: "your "
 - trigger: "ts.,"
   replace: "its "
 - trigger: "ovr.,"
   replace: "over "
 - trigger: "ths.,"
   replace: "these "
 - trigger: "2.,"
   replace: "two "
 - trigger: "s.,"
   replace: "see "
 - trigger: "mr.,"
   replace: "more "
 - trigger: "tm.,"
   replace: "time "
 - trigger: "us.,"
   replace: "use "
 - trigger: "mn.,"
   replace: "man "
 - trigger: "mk.,"
   replace: "make "
 - trigger: "sch.,"
   replace: "such "
 - trigger: "hr.,"
   replace: "here "
 - trigger: "wy.,"
   replace: "way "
 - trigger: "wl.,"
   replace: "well "
 - trigger: "als.,"
   replace: "also "
 - trigger: "ny.,"
   replace: "any "
 - trigger: "mst.,"
   replace: "must "
 - trigger: "hm.,"
   replace: "home "
 - trigger: "evn.,"
   replace: "even "
 - trigger: "mny.,"
   replace: "many "
 - trigger: "bk.,"
   replace: "back "
 - trigger: "aftr.,"
   replace: "after "
 - trigger: "yrs.,"
   replace: "years "
 - trigger: "wt.,"
   replace: "want "
 - trigger: "whr.,"
   replace: "where "
 - trigger: "ths.,"
   replace: "those "
 - trigger: "mst.,"
   replace: "most "
 - trigger: "ppl.,"
   replace: "people "
 - trigger: "knw.,"
   replace: "know "
 - trigger: "tk.,"
   replace: "take "
 - trigger: "1st.,"
   replace: "first "
 - trigger: "wrk.,"
   replace: "work "
 - trigger: "gd.,"
   replace: "good "
 - trigger: "mch.,"
   replace: "much "
 - trigger: "grt.,"
   replace: "great "
 - trigger: "bfr.,"
   replace: "before "
 - trigger: "dy.,"
   replace: "day "
 - trigger: "sm.,"
   replace: "same "
 - trigger: "rgt.,"
   replace: "right "
 - trigger: "thnk.,"
   replace: "think "
 - trigger: "r.,"
   replace: "our "
 - trigger: "old.,"
   replace: "old "
 - trigger: "fnd.,"
   replace: "find "
 - trigger: "lng.,"
   replace: "long "
 - trigger: "stl.,"
   replace: "still "
 - trigger: "lst.,"
   replace: "last "
 - trigger: "nvr.,"
   replace: "never "
 - trigger: "gv.,"
   replace: "give "
 - trigger: "whl.,"
   replace: "while "
 - trigger: "antr.,"
   replace: "another "
 - trigger: "plc.,"
   replace: "place "
 - trigger: "pt.,"
   replace: "put "
 - trigger: "nw.,"
   replace: "new "
 - trigger: "undr.,"
   replace: "under "
 - trigger: "gt.,"
   replace: "get "
 - trigger: "evry.,"
   replace: "every "
 - trigger: "own.,"
   replace: "own "
 - trigger: "stry.,"
   replace: "story "
 - trigger: "lv.,"
   replace: "leave "
 - trigger: "end.,"
   replace: "end "
 - trigger: "sm.,"
   replace: "seem "
 - trigger: "fw.,"
   replace: "few "
 - trigger: "try.,"
   replace: "try "
 - trigger: "2nd.,"
   replace: "second "
 - trigger: "strt.,"
   replace: "start "
 - trigger: "trn.,"
   replace: "turn "
 - trigger: "hlp.,"
   replace: "help "
 - trigger: "mght.,"
   replace: "might "
 - trigger: "lv.,"
   replace: "live "
 - trigger: "prt.,"
   replace: "part "
 - trigger: "sml.,"
   replace: "small "
 - trigger: "wt.,"
   replace: "want "
 - trigger: "by.,"
   replace: "boy "
 - trigger: "cm.,"
   replace: "came "
 - trigger: "shw.,"
   replace: "show "
 - trigger: "tht.,"
   replace: "thought "
 - trigger: "hs.,"
   replace: "house "
 - trigger: "frm.,"
   replace: "form "
 - trigger: "ar.,"
   replace: "air "
 - trigger: "hnd.,"
   replace: "hand "
 - trigger: "end.,"
   replace: "end "
 - trigger: "lrg.,"
   replace: "large "
 - trigger: "st.,"
   replace: "set "
 - trigger: "hgh.,"
   replace: "high "
 - trigger: "grp.,"
   replace: "group "
 - trigger: "yng.,"
   replace: "young "
 - trigger: "imprt.,"
   replace: "important "
 - trigger: "fw.,"
   replace: "few "
 - trigger: "kp.,"
   replace: "keep "
 - trigger: "sd.,"
   replace: "side "
 - trigger: "lrg.,"
   replace: "large "
 - trigger: "ordr.,"
   replace: "order "
 - trigger: "thru.,"
   replace: "through "
 - trigger: "mst.,"
   replace: "must "
 - trigger: "hd.,"
   replace: "head "
 - trigger: "lgt.,"
   replace: "light "
 - trigger: "knd.,"
   replace: "kind "
 - trigger: "cty.,"
   replace: "city "
 - trigger: "cntry.,"
   replace: "country "
 - trigger: "dffrnt.,"
   replace: "different "
 - trigger: "1ce.,"
   replace: "once "
 - trigger: "mthr.,"
   replace: "mother "
 - trigger: "awy.,"
   replace: "away "
 - trigger: "fthr.,"
   replace: "father "
 - trigger: "ngt.,"
   replace: "night "
 - trigger: "cr.,"
   replace: "car "
 - trigger: "ngh.,"
   replace: "enough "
 - trigger: "cls.,"
   replace: "close "
 - trigger: "drng.,"
   replace: "during "
 - trigger: "ndd.,"
   replace: "indeed "
 - trigger: "pwr.,"
   replace: "power "
 - trigger: "alng.,"
   replace: "along "
 - trigger: "vc.,"
   replace: "voice "
 - trigger: "wr.,"
   replace: "war "
 - trigger: "tgr.,"
   replace: "together "
 - trigger: "bth.,"
   replace: "both "
 - trigger: "frm.,"
   replace: "form "
 - trigger: "rnd.,"
   replace: "round "
 - trigger: "bk.,"
   replace: "book "
 - trigger: "own.,"
   replace: "own "
 - trigger: "fmly.,"
   replace: "family "
 - trigger: "lv.,"
   replace: "leave "
 - trigger: "wtr.,"
   replace: "water "
 - trigger: "hld.,"
   replace: "hold "
 - trigger: "rn.,"
   replace: "run "
 - trigger: "trn.,"
   replace: "turn "
 - trigger: "fw.,"
   replace: "few "
 - trigger: "stnd.,"
   replace: "stand "
 - trigger: "br.,"
   replace: "bear "
 - trigger: "sns.,"
   replace: "sense "
 - trigger: "sm.,"
   replace: "seem "
 - trigger: "bld.,"
   replace: "build "
 - trigger: "lv.,"
   replace: "live "
 - trigger: "brng.,"
   replace: "bring "
 - trigger: "lst.,"
   replace: "lost "
 - trigger: "grl.,"
   replace: "girl "
 - trigger: "alwys.,"
   replace: "always "
 - trigger: "abl.,"
   replace: "able "
 - trigger: "thr.,"
   replace: "either "
 - trigger: "plse.,"
   replace: "please "
 - trigger: "evr.,"
   replace: "ever "
 - trigger: "sd.,"
   replace: "side "
 - trigger: "nthng.,"
   replace: "nothing "
 - trigger: "crs.,"
   replace: "course "
 - trigger: "kp.,"
   replace: "keep "
 - trigger: "nxt.,"
   replace: "next "
 - trigger: "2nd.,"
   replace: "second "
 - trigger: "ls.,"
   replace: "less "
 - trigger: "id.,"
   replace: "idea "
 - trigger: "alms.,"
   replace: "almost "
 - trigger: "prty.,"
   replace: "pretty "
 - trigger: "lv.,"
   replace: "leave "
 - trigger: "opn.,"
   replace: "open "
 - trigger: "dr.,"
   replace: "door "
 - trigger: "lfe.,"
   replace: "life "
 - trigger: "untl.,"
   replace: "until "
 - trigger: "ft.,"
   replace: "foot "
 - trigger: "oftn.,"
   replace: "often "
 - trigger: "1ce.,"
   replace: "once "
 - trigger: "wht.,"
   replace: "white "
 - trigger: "wtr.,"
   replace: "water "
 - trigger: "lgt.,"
   replace: "light "
 - trigger: "ngh.,"
   replace: "enough "
 - trigger: "bgn.,"
   replace: "begin "
 - trigger: "strt.,"
   replace: "start "
 - trigger: "mght.,"
   replace: "might "
 - trigger: "wlk.,"
   replace: "walk "
 - trigger: "prsnt.,"
   replace: "present "
 - trigger: "untl.,"
   replace: "until "
 - trigger: "thgh.,"
   replace: "though "
 - trigger: "cty.,"
   replace: "city "
 - trigger: "frnt.,"
   replace: "front "
 - trigger: "wtht.,"
   replace: "without "
 - trigger: "trn.,"
   replace: "turn "
 - trigger: "lrn.,"
   replace: "learn "
 - trigger: "plnt.,"
   replace: "plant "
 - trigger: "cvr.,"
   replace: "cover "
 - trigger: "fd.,"
   replace: "food "
 - trigger: "sn.,"
   replace: "sun "
 - trigger: "4.,"
   replace: "four "
 - trigger: "btwn.,"
   replace: "between "
 - trigger: "stt.,"
   replace: "state "
 - trigger: "kp.,"
   replace: "keep "
 - trigger: "ey.,"
   replace: "eye "
 - trigger: "nvr.,"
   replace: "never "
 - trigger: "lst.,"
   replace: "last "
 - trigger: "lt.,"
   replace: "let "
 - trigger: "tht.,"
   replace: "thought "
 - trigger: "frm.,"
   replace: "farm "
 - trigger: "smthg.,"
   replace: "something "
 - trigger: "fw.,"
   replace: "few "
 - trigger: "mn.,"
   replace: "mean "
 - trigger: "2nd.,"
   replace: "second "
 - trigger: "hlp.,"
   replace: "help "
 - trigger: "trn.,"
   replace: "turn "
 - trigger: "twn.,"
   replace: "town "
 - trigger: "wrld.,"
   replace: "world "
 - trigger: "nr.,"
   replace: "near "
 - trigger: "shw.,"
   replace: "show "
 - trigger: "lv.,"
   replace: "live "
 - trigger: "tr.,"
   replace: "tree "
 - trigger: "hrd.,"
   replace: "hard "
 - trigger: "strt.,"
   replace: "start "
 - trigger: "mght.,"
   replace: "might "
 - trigger: "stry.,"
   replace: "story "
 - trigger: "sw.,"
   replace: "saw "
 - trigger: "lft.,"
   replace: "left "
 - trigger: "lte.,"
   replace: "late "
 - trigger: "rn.,"
   replace: "run "
 - trigger: "dnt.,"
   replace: "don't "
 - trigger: "whl.,"
   replace: "while "
 - trigger: "prss.,"
   replace: "press "
 - trigger: "cls.,"
   replace: "close "
 - trigger: "rl.,"
   replace: "real "
 - trigger: "ngt.,"
   replace: "night "
 - trigger: "sm.,"
   replace: "seem "
 - trigger: "fthr.,"
   replace: "father "
 - trigger: "fw.,"
   replace: "few "
 - trigger: "nrth.,"
   replace: "north "
 - trigger: "opn.,"
   replace: "open "
 - trigger: "stp.,"
   replace: "stop "
 - trigger: "cr.,"
   replace: "car "
 - trigger: "1ce.,"
   replace: "once "
 - trigger: "bk.,"
   replace: "book "
 - trigger: "tk.,"
   replace: "took "
 - trigger: "pnt.,"
   replace: "point "
 - trigger: "tr.,"
   replace: "tree "
 - trigger: "nthng.,"
   replace: "nothing "
 - trigger: "bgn.,"
   replace: "begin "
 - trigger: "id.,"
   replace: "idea "
 - trigger: "fsh.,"
   replace: "fish "
 - trigger: "wrk.,"
   replace: "work "
 - trigger: "frm.,"
   replace: "form "
 - trigger: "rm.,"
   replace: "room "
 - trigger: "frnd.,"
   replace: "friend "
 - trigger: "et.,"
   replace: "eat "
 - trigger: "1ce.,"
   replace: "once "
 - trigger: "by.,"
   replace: "boy "
 - trigger: "snce.,"
   replace: "since "
 - trigger: "gn.,"
   replace: "gone "
 - trigger: "bdy.,"
   replace: "body "
 - trigger: "ply.,"
   replace: "play "
 - trigger: "hr.,"
   replace: "hear "
 - trigger: "ct.,"
   replace: "cut "
 - trigger: "old.,"
   replace: "old "
 - trigger: "stl.,"
   replace: "still "
 - trigger: "to.,"
   replace: "too "
 - trigger: "4.,"
   replace: "four "
 - trigger: "lgt.,"
   replace: "light "
 - trigger: "bng.,"
   replace: "being "
 - trigger: "fmly.,"
   replace: "family "
 - trigger: "mthr.,"
   replace: "mother "
 - trigger: "lrn.,"
   replace: "learn "
 - trigger: "fthr.,"
   replace: "father "
 - trigger: "twrd.,"
   replace: "toward "
 - trigger: "any1.,"
   replace: "anyone "
 - trigger: "agn.,"
   replace: "again "
 - trigger: "hs.,"
   replace: "house "
 - trigger: "cntry.,"
   replace: "country "
 - trigger: "bk.,"
   replace: "back "
 - trigger: "hld.,"
   replace: "hold "
 - trigger: "prt.,"
   replace: "part "