local db = require('dashboard')
db.custom_header = {
  "                                                   ",
  "                                                   ",
  "                                                   ",
  " ███▄    █ ▓█████  ▒█████   ██▒   █▓ ██▓ ███▄ ▄███▓",
  " ██ ▀█   █ ▓█   ▀ ▒██▒  ██▒▓██░   █▒▓██▒▓██▒▀█▀ ██▒",
  "▓██  ▀█ ██▒▒███   ▒██░  ██▒ ▓██  █▒░▒██▒▓██    ▓██░",
  "▓██▒  ▐▌██▒▒▓█  ▄ ▒██   ██░  ▒██ █░░░██░▒██    ▒██ ",
  "▒██░   ▓██░░▒████▒░ ████▓▒░   ▒▀█░  ░██░▒██▒   ░██▒",
  "░ ▒░   ▒ ▒ ░░ ▒░ ░░ ▒░▒░▒░    ░ ▐░  ░▓  ░ ▒░   ░  ░",
  "░ ░░   ░ ▒░ ░ ░  ░  ░ ▒ ▒░    ░ ░░   ▒ ░░  ░      ░",
  "   ░   ░ ░    ░   ░ ░ ░ ▒       ░░   ▒ ░░      ░   ",
  "         ░    ░  ░    ░ ░        ░   ░         ░   ",
  "                                ░                  ",
  "                                                   ",
}

db.custom_center = {
  { icon = '  ',
    desc = 'Recent Files                            ',
    action = 'Telescope oldfiles',
    shortcut = 'SPC f o' },
  { icon = '  ',
    desc = 'Find File                               ',
    action = 'Telescope frecency frecency default_text=:CWD:',
    shortcut = 'SPC p  ' },
  { icon = '洛 ',
    desc = 'New File                                ',
    action = 'DashboardNewFile',
    shortcut = 'SPC ?  ' },
  { icon = '  ',
    desc = 'Bookmarks                               ',
    action = 'Telescope marks',
    shortcut = 'SPC f ?' },
  { icon = '  ',
    desc = 'File Browser                            ',
    action = 'NvimTreeOpen',
    shortcut = 'SPC f b' },
  { icon = '  ',
    desc = 'Find Word                               ',
    action = 'Telescope live_grep',
    shortcut = 'SPC f w' },
  { icon = '  ',
    desc = 'Load Last Session                       ',
    shortcut = 'SPC s l',
    action = 'SessionLoad' },
}
