require("octo").setup({
  default_remote = { "upstream", "origin" }, -- order to try remotes
  reaction_viewer_hint_icon = "", -- marker for user reactions
  user_icon = " ", -- user icon
  timeline_marker = "", -- timeline marker
  timeline_indent = "2", -- timeline indentation
  right_bubble_delimiter = "", -- Bubble delimiter
  left_bubble_delimiter = "", -- Bubble delimiter
  github_hostname = "", -- GitHub Enterprise host
  snippet_context_lines = 4, -- number or lines around commented lines
  file_panel = {
    size = 10, -- changed files panel rows
    use_icons = true, -- use web-devicons in file panel
  },
  mappings = {
    issue = {
      -- close_issue = "lic", -- close issue
      -- reopen_issue = "lio", -- reopen issue
      -- list_issues = "lil", -- list open issues on same repo
      reload = "<C-r>", -- reload issue
      open_in_browser = "<C-b>", -- open issue in browser
      copy_url = "<C-y>", -- copy url to system clipboard
      -- add_assignee = "laa", -- add assignee
      -- remove_assignee = "lad", -- remove assignee
      -- create_label = "llc", -- create label
      -- add_label = "lla", -- add label
      -- remove_label = "lld", -- remove label
      -- goto_issue = "lgi", -- navigate to a local repo issue
      -- add_comment = "lca", -- add comment
      -- delete_comment = "lcd", -- delete comment
      next_comment = "]c", -- go to next comment
      prev_comment = "[c", -- go to previous comment
      -- react_hooray = "lrp", -- add/remove 🎉 reaction
      -- react_heart = "lrh", -- add/remove ❤️ reaction
      -- react_eyes = "lre", -- add/remove 👀 reaction
      -- react_thumbs_up = "lr+", -- add/remove 👍 reaction
      -- react_thumbs_down = "lr-", -- add/remove 👎 reaction
      -- react_rocket = "lrr", -- add/remove 🚀 reaction
      -- react_laugh = "lrl", -- add/remove 😄 reaction
      -- react_confused = "lrc", -- add/remove 😕 reaction
    },
    pull_request = {
      -- checkout_pr = "lpo", -- checkout PR
      -- merge_pr = "lpm", -- merge PR
      -- list_commits = "lpc", -- list PR commits
      -- list_changed_files = "lpf", -- list PR changed files
      -- show_pr_diff = "lpd", -- show PR diff
      -- add_reviewer = "lva", -- add reviewer
      -- remove_reviewer = "lvd", -- remove reviewer request
      -- close_issue = "lic", -- close PR
      -- reopen_issue = "lio", -- reopen PR
      -- list_issues = "lil", -- list open issues on same repo
      reload = "<C-r>", -- reload PR
      open_in_browser = "<C-b>", -- open PR in browser
      copy_url = "<C-y>", -- copy url to system clipboard
      -- add_assignee = "laa", -- add assignee
      -- remove_assignee = "lad", -- remove assignee
      -- create_label = "llc", -- create label
      -- add_label = "lla", -- add label
      -- remove_label = "lld", -- remove label
      -- goto_issue = "lgi", -- navigate to a local repo issue
      -- add_comment = "lca", -- add comment
      -- delete_comment = "lcd", -- delete comment
      next_comment = "]c", -- go to next comment
      prev_comment = "[c", -- go to previous comment
      -- react_hooray = "lrp", -- add/remove 🎉 reaction
      -- react_heart = "lrh", -- add/remove ❤️ reaction
      -- react_eyes = "lre", -- add/remove 👀 reaction
      -- react_thumbs_up = "lr+", -- add/remove 👍 reaction
      -- react_thumbs_down = "lr-", -- add/remove 👎 reaction
      -- react_rocket = "lrr", -- add/remove 🚀 reaction
      -- react_laugh = "lrl", -- add/remove 😄 reaction
      -- react_confused = "lrc", -- add/remove 😕 reaction
    },
    review_thread = {
      -- goto_issue = "lgi", -- navigate to a local repo issue
      -- add_comment = "lca", -- add comment
      -- add_suggestion = "lsa", -- add suggestion
      -- delete_comment = "lcd", -- delete comment
      next_comment = "]c", -- go to next comment
      prev_comment = "[c", -- go to previous comment
      select_next_entry = "]q", -- move to previous changed file
      select_prev_entry = "[q", -- move to next changed file
      close_review_tab = "<C-c>", -- close review tab
      -- react_hooray = "lrp", -- add/remove 🎉 reaction
      -- react_heart = "lrh", -- add/remove ❤️ reaction
      -- react_eyes = "lre", -- add/remove 👀 reaction
      -- react_thumbs_up = "lr+", -- add/remove 👍 reaction
      -- react_thumbs_down = "lr-", -- add/remove 👎 reaction
      -- react_rocket = "lrr", -- add/remove 🚀 reaction
      -- react_laugh = "lrl", -- add/remove 😄 reaction
      -- react_confused = "lrc", -- add/remove 😕 reaction
    },
    submit_win = {
      approve_review = "<C-a>", -- approve review
      comment_review = "<C-m>", -- comment review
      request_changes = "<C-r>", -- request changes review
      close_review_tab = "<C-c>", -- close review tab
    },
    review_diff = {
      -- add_review_comment = "lca", -- add a new review comment
      -- add_review_suggestion = "lsa", -- add a new review suggestion
      -- focus_files = "le", -- move focus to changed file panel
      -- toggle_files = "lb", -- hide/show changed files panel
      next_thread = "]t", -- move to next thread
      prev_thread = "[t", -- move to previous thread
      select_next_entry = "]q", -- move to previous changed file
      select_prev_entry = "[q", -- move to next changed file
      close_review_tab = "<C-c>", -- close review tab
      -- toggle_viewed = "ll", -- toggle viewer viewed state
    },
    file_panel = {
      next_entry = "j", -- move to next changed file
      prev_entry = "k", -- move to previous changed file
      select_entry = "<cr>", -- show selected changed file diffs
      refresh_files = "R", -- refresh changed files panel
      -- focus_files = "le", -- move focus to changed file panel
      -- toggle_files = "lb", -- hide/show changed files panel
      select_next_entry = "]q", -- move to previous changed file
      select_prev_entry = "[q", -- move to next changed file
      close_review_tab = "<C-c>", -- close review tab
      -- toggle_viewed = "ll", -- toggle viewer viewed state
    },
  },
})
