# espanso configuration file
backend: Clipboard
# fast_inject: false
# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ".,ee"
    replace: "danelipscombe@gmail.com"

  - trigger: ".,ep"
    replace: "dlip1@protonmail.com"
    
  - trigger: ".,ew"
    replace: "dane.lipscombe@playtravel.com.au"

  # Dates

  - trigger: ".,da"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ".,dd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ".,dh"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "# %d %a"
  - trigger: ".,tt"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  # Shell commands
  - trigger: ".,ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.co"

  # Vim
  - trigger: ".,."
    replace: "\\(.*\\)"
