# espanso configuration file
#backend: Clipboard
# fast_inject: false
# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Dates
  - trigger: ".,da"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ".,dd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ".,dh"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "# %d %a"
  - trigger: ".,tt"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  # Shell commands
  - trigger: ".,ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.co"

  # Vim
  - trigger: "..,"
    replace: "\\(.*\\)"

  # Personal
  - trigger: "@.,"
    replace: "danelipscombe@gmail.com"
  - trigger: "@p.,"
    replace: "dlip1@protonmail.com"
  - trigger: "@w.,"
    replace: "dane.lipscombe@playtravel.com.au"
  - trigger: "dl.,"
    replace: "Dane Lipscombe"
  - trigger: "zD.,"
    replace: "Dane"
  - trigger: "zL.,"
    replace: "Lipscombe"

  # MACROS START
  - trigger: "a"
    replace: "a"
    propagate_case: true
    word: true
  - trigger: "i"
    replace: "I"
    propagate_case: true
    word: true
  - trigger: "t"
    replace: "the"
    propagate_case: true
    word: true
  - trigger: "x"
    replace: "and"
    propagate_case: true
    word: true
  - trigger: "u"
    replace: "you"
    propagate_case: true
    word: true
  - trigger: "th"
    replace: "that"
    propagate_case: true
    word: true
  - trigger: "w"
    replace: "was"
    propagate_case: true
    word: true
  - trigger: "f"
    replace: "for"
    propagate_case: true
    word: true
  - trigger: "ar"
    replace: "are"
    propagate_case: true
    word: true
  - trigger: "wi"
    replace: "with"
    propagate_case: true
    word: true
  - trigger: "h"
    replace: "his"
    propagate_case: true
    word: true
  - trigger: "the"
    replace: "they"
    propagate_case: true
    word: true
  - trigger: "o"
    replace: "one"
    propagate_case: true
    word: true
  - trigger: "ha"
    replace: "have"
    propagate_case: true
    word: true
  - trigger: "thi"
    replace: "this"
    propagate_case: true
    word: true
  - trigger: "fr"
    replace: "from"
    propagate_case: true
    word: true
  - trigger: "hd"
    replace: "had"
    propagate_case: true
    word: true
  - trigger: "ho"
    replace: "hot"
    propagate_case: true
    word: true
  - trigger: "b"
    replace: "but"
    propagate_case: true
    word: true
  - trigger: "s"
    replace: "some"
    propagate_case: true
    word: true
  - trigger: "wh"
    replace: "what"
    propagate_case: true
    word: true
  - trigger: "thr"
    replace: "there"
    propagate_case: true
    word: true
  - trigger: "c"
    replace: "can"
    propagate_case: true
    word: true
  - trigger: "ou"
    replace: "out"
    propagate_case: true
    word: true
  - trigger: "ot"
    replace: "other"
    propagate_case: true
    word: true
  - trigger: "wr"
    replace: "were"
    propagate_case: true
    word: true
  - trigger: "al"
    replace: "all"
    propagate_case: true
    word: true
  - trigger: "yr"
    replace: "your"
    propagate_case: true
    word: true
  - trigger: "whe"
    replace: "when"
    propagate_case: true
    word: true
  - trigger: "us"
    replace: "use"
    propagate_case: true
    word: true
  - trigger: "wo"
    replace: "word"
    propagate_case: true
    word: true
  - trigger: "hw"
    replace: "how"
    propagate_case: true
    word: true
  - trigger: "sa"
    replace: "said"
    propagate_case: true
    word: true
  - trigger: "e"
    replace: "each"
    propagate_case: true
    word: true
  - trigger: "sh"
    replace: "she"
    propagate_case: true
    word: true
  - trigger: "whi"
    replace: "which"
    propagate_case: true
    word: true
  - trigger: "thei"
    replace: "their"
    propagate_case: true
    word: true
  - trigger: "ti"
    replace: "time"
    propagate_case: true
    word: true
  - trigger: "wl"
    replace: "will"
    propagate_case: true
    word: true
  - trigger: "wa"
    replace: "way"
    propagate_case: true
    word: true
  - trigger: "ab"
    replace: "about"
    propagate_case: true
    word: true
  - trigger: "m"
    replace: "many"
    propagate_case: true
    word: true
  - trigger: "thn"
    replace: "then"
    propagate_case: true
    word: true
  - trigger: "thm"
    replace: "them"
    propagate_case: true
    word: true
  - trigger: "wou"
    replace: "would"
    propagate_case: true
    word: true
  - trigger: "wri"
    replace: "write"
    propagate_case: true
    word: true
  - trigger: "l"
    replace: "like"
    propagate_case: true
    word: true
  - trigger: "ths"
    replace: "these"
    propagate_case: true
    word: true
  - trigger: "hr"
    replace: "her"
    propagate_case: true
    word: true
  - trigger: "lo"
    replace: "long"
    propagate_case: true
    word: true
  - trigger: "mk"
    replace: "make"
    propagate_case: true
    word: true
  - trigger: "thin"
    replace: "thing"
    propagate_case: true
    word: true
  - trigger: "se"
    replace: "see"
    propagate_case: true
    word: true
  - trigger: "hi"
    replace: "him"
    propagate_case: true
    word: true
  - trigger: "tw"
    replace: "two"
    propagate_case: true
    word: true
  - trigger: "hs"
    replace: "has"
    propagate_case: true
    word: true
  - trigger: "lk"
    replace: "look"
    propagate_case: true
    word: true
  - trigger: "mo"
    replace: "more"
    propagate_case: true
    word: true
  - trigger: "d"
    replace: "day"
    propagate_case: true
    word: true
  - trigger: "co"
    replace: "could"
    propagate_case: true
    word: true
  - trigger: "cm"
    replace: "come"
    propagate_case: true
    word: true
  - trigger: "di"
    replace: "did"
    propagate_case: true
    word: true
  - trigger: "sn"
    replace: "sound"
    propagate_case: true
    word: true
  - trigger: "ms"
    replace: "most"
    propagate_case: true
    word: true
  - trigger: "n"
    replace: "number"
    propagate_case: true
    word: true
  - trigger: "hu"
    replace: "who"
    propagate_case: true
    word: true
  - trigger: "ov"
    replace: "over"
    propagate_case: true
    word: true
  - trigger: "k"
    replace: "know"
    propagate_case: true
    word: true
  - trigger: "wt"
    replace: "water"
    propagate_case: true
    word: true
  - trigger: "tha"
    replace: "than"
    propagate_case: true
    word: true
  - trigger: "ca"
    replace: "call"
    propagate_case: true
    word: true
  - trigger: "fi"
    replace: "first"
    propagate_case: true
    word: true
  - trigger: "p"
    replace: "people"
    propagate_case: true
    word: true
  - trigger: "mi"
    replace: "may"
    propagate_case: true
    word: true
  - trigger: "dw"
    replace: "down"
    propagate_case: true
    word: true
  - trigger: "si"
    replace: "side"
    propagate_case: true
    word: true
  - trigger: "bn"
    replace: "been"
    propagate_case: true
    word: true
  - trigger: "nw"
    replace: "now"
    propagate_case: true
    word: true
  - trigger: "fn"
    replace: "find"
    propagate_case: true
    word: true
  - trigger: "ne"
    replace: "any"
    propagate_case: true
    word: true
  - trigger: "nu"
    replace: "new"
    propagate_case: true
    word: true
  - trigger: "wor"
    replace: "work"
    propagate_case: true
    word: true
  - trigger: "pa"
    replace: "part"
    propagate_case: true
    word: true
  - trigger: "ta"
    replace: "take"
    propagate_case: true
    word: true
  - trigger: "g"
    replace: "get"
    propagate_case: true
    word: true
  - trigger: "pl"
    replace: "place"
    propagate_case: true
    word: true
  - trigger: "md"
    replace: "made"
    propagate_case: true
    word: true
  - trigger: "li"
    replace: "live"
    propagate_case: true
    word: true
  - trigger: "whr"
    replace: "where"
    propagate_case: true
    word: true
  - trigger: "af"
    replace: "after"
    propagate_case: true
    word: true
  - trigger: "ba"
    replace: "back"
    propagate_case: true
    word: true
  - trigger: "lt"
    replace: "little"
    propagate_case: true
    word: true
  - trigger: "onl"
    replace: "only"
    propagate_case: true
    word: true
  - trigger: "r"
    replace: "round"
    propagate_case: true
    word: true
  - trigger: "ma"
    replace: "man"
    propagate_case: true
    word: true
  - trigger: "ya"
    replace: "year"
    propagate_case: true
    word: true
  - trigger: "cam"
    replace: "came"
    propagate_case: true
    word: true
  - trigger: "sho"
    replace: "show"
    propagate_case: true
    word: true
  - trigger: "ev"
    replace: "every"
    propagate_case: true
    word: true
  - trigger: "gd"
    replace: "good"
    propagate_case: true
    word: true
  - trigger: "gi"
    replace: "give"
    propagate_case: true
    word: true
  - trigger: "ow"
    replace: "our"
    propagate_case: true
    word: true
  - trigger: "un"
    replace: "under"
    propagate_case: true
    word: true
  - trigger: "na"
    replace: "name"
    propagate_case: true
    word: true
  - trigger: "v"
    replace: "very"
    propagate_case: true
    word: true
  - trigger: "thro"
    replace: "through"
    propagate_case: true
    word: true
  - trigger: "j"
    replace: "just"
    propagate_case: true
    word: true
  - trigger: "fo"
    replace: "form"
    propagate_case: true
    word: true
  - trigger: "mu"
    replace: "much"
    propagate_case: true
    word: true
  - trigger: "gr"
    replace: "great"
    propagate_case: true
    word: true
  - trigger: "thnk"
    replace: "think"
    propagate_case: true
    word: true
  - trigger: "sy"
    replace: "say"
    propagate_case: true
    word: true
  - trigger: "hl"
    replace: "help"
    propagate_case: true
    word: true
  - trigger: "lw"
    replace: "low"
    propagate_case: true
    word: true
  - trigger: "ln"
    replace: "line"
    propagate_case: true
    word: true
  - trigger: "bf"
    replace: "before"
    propagate_case: true
    word: true
  - trigger: "tu"
    replace: "turn"
    propagate_case: true
    word: true
  - trigger: "cs"
    replace: "cause"
    propagate_case: true
    word: true
  - trigger: "sm"
    replace: "same"
    propagate_case: true
    word: true
  - trigger: "mn"
    replace: "mean"
    propagate_case: true
    word: true
  - trigger: "df"
    replace: "differ"
    propagate_case: true
    word: true
  - trigger: "mv"
    replace: "move"
    propagate_case: true
    word: true
  - trigger: "ri"
    replace: "right"
    propagate_case: true
    word: true
  - trigger: "bo"
    replace: "boy"
    propagate_case: true
    word: true
  - trigger: "ol"
    replace: "old"
    propagate_case: true
    word: true

  # MACROS END
