units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2
points:
  zones:
    matrix:
      rotate: -30
      key:
        padding: 1ky
      columns:
        pinky:
          key:
            splay: 15
        ring:
          key:
            stagger: 3
            spread: 28
            splay: -10
        middle:
          key:
            stagger: 10
            spread: 23
            splay: -5
        index:
          key:
            stagger: -8
            spread: 23
            splay: -5
      rows:
        bottom:
        top:
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_index_bottom
        shift: [26, -10]
      columns:
        inner:
          key:
            width: 1.5kx
            splay: -20
            rotate: 90
        outer:
          key:
            width: 1.5kx
            rotate: 90
      rows:
        cluster:
          shift: [0, -2ky]
  mirror: &mirror
    ref: matrix_index_top
    distance: 2.5kx
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
    - what: rectangle
      where: thumbs_inner_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: thumbs_outer_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: mirror_thumbs_inner_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: mirror_thumbs_outer_cluster
      size: [1.5kx,ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_index_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_index_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.6py]
        - ref: mirror_thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [-0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.6py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
  combo:
    - name: board
    - operation: subtract
      name: keys