units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2
points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      rotate: -30
      key:
        padding: 1ky
      columns:
        pinky:
          key:
            splay: 15
          rows:
            top.mcu_pin: GP26
            bottom.mcu_pin: GP12
            top.mirror.mcu_pin: GP3
            bottom.mirror.mcu_pin: GP7
        ring:
          key:
            stagger: 3
            spread: 28
            splay: -10
          rows:
            top.mcu_pin: GP27
            bottom.mcu_pin: GP13
            top.mirror.mcu_pin: GP2
            bottom.mirror.mcu_pin: GP6
        middle:
          key:
            stagger: 10
            spread: 23
            splay: -5
          rows:
            top.mcu_pin: GP28
            bottom.mcu_pin: GP14
            top.mirror.mcu_pin: GP1
            bottom.mirror.mcu_pin: GP5
        index:
          key:
            stagger: -8
            spread: 23
            splay: -5
          rows:
            top.mcu_pin: GP29
            bottom.mcu_pin: GP15
            top.mirror.mcu_pin: GP0
            bottom.mirror.mcu_pin: GP4
      rows:
        bottom:
        top:
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_index_bottom
        shift: [26, -10]
      columns:
        inner:
          key:
            width: 1.5kx
            splay: -20
            rotate: 90
            mcu_pin: GP11
            mirror.mcu_pin: GP8
        outer:
          key:
            width: 1.5kx
            rotate: 90
            mcu_pin: GP10
            mirror.mcu_pin: GP9
      rows:
        cluster:
          shift: [0, -2ky]
  mirror: &mirror
    ref: matrix_index_top
    distance: 2.5kx
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
    - what: rectangle
      where: thumbs_inner_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: thumbs_outer_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: mirror_thumbs_inner_cluster
      size: [1.5kx,ky-0.5]
    - what: rectangle
      where: mirror_thumbs_outer_cluster
      size: [1.5kx,ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_index_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_index_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.6py]
        - ref: mirror_thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: mirror_thumbs_inner_cluster
          shift: [-0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: mirror_thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [0.75px,-0.5py]
        - ref: thumbs_outer_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,-0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.75px,0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.6py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  tutorial:
    outlines:
      main:
        outline:
          board
    footprints:
      # choc_hotswap:
      #   what: choc
      #   where: true
      #   params:
      #     keycaps: true
      #     hotswap: true
      #     from: "{{mcu_pin}}"
      #     to: GND
      choc:
        what: choc
        where: true
        adjust:
          rotate: 180
        params:
          keycaps: true
          from: "{{mcu_pin}}"
          to: GND
      mcu:
        what: rp2040zero
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-10,-24]
        params:
          reverse: true
          GND: GND
cases:
  bottom:
    - name: board
      extrude: 1