map s scrollDown
map f scrollUp
map r scrollLeft
map t scrollRight
map c scrollPageUp
map a LinkHints.activateMode
map A LinkHints.activateModeToOpenInNewTab
map w goBack
map p goForward
map <space> Vomnibar.activateTabSelection
