# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/92c6b3bd-a760-40b0-9785-79b62e513dca";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/25cfe3ad-8f09-49a2-a036-683fc4b9a73f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D798-3E35";
      fsType = "vfat";
    };

  swapDevices = [{ device = "/.swapfile"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
