#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe


ps -alh | grep xmobar_control_script | awk '{print $3}' | xargs kill

pkill stalonetray
pkill picom
pkill xmobar
pkill xmobar

