#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot compton or picom if it exists
# if [ -x "$(command -v picom)" ]; then
#   picom --config $SCRIPTPATH/picom.conf  --experimental-backends &> /dev/null &
# fi

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

if [ -x "$(command -v trayer)" ]; then
  trayer --edge top --tint 0x313846 --transparent true --alpha 0 --width 10 --height 22 --heighttype pixel --align right --distancefrom right --distance 400 &> /dev/null &
fi

if [ -x "$(command -v betterlockscreen)" ]; then
  betterlockscreen -w dim &> /dev/null &
fi

if [ -x "$(command -v update-wallpaper)" ]; then
  update-wallpaper &> /dev/null &
fi

index=0
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read size
do
   leftwm-state -w $index -t $SCRIPTPATH/template.liquid | xmobar -p "$size" $SCRIPTPATH/xmobar-config.hs &
   let index=index+1
done