# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/3c17bc3c-872a-4483-a6ec-29cb1b5a14d1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/6b9e61d0-b58c-475b-a9fd-d1e2ed0217f5";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/0B69-96D6";
      fsType = "vfat";
    };

  boot.initrd.secrets = { "lukskey" = "/root/lukskey"; };

  fileSystems."/media/media" = {
    device = "/dev/disk/by-uuid/ffea1765-0616-4311-ac3b-fde6e83ef011"; # UUID for /dev/mapper/media
    fsType = "btrfs";
    encrypted = {
      enable = true;
      label = "media";
      blkDev =
        "/dev/disk/by-uuid/7c1152e4-b2a0-421a-815a-ea10ee700667"; # UUID for /dev/sda1
      keyFile = "/lukskey";
    };
  };
  fileSystems."/media/media2" = {
    device = "/dev/disk/by-uuid/bd148b15-4950-4da8-9fd1-17d8a32390d5"; # UUID for /dev/mapper/media2
    fsType = "btrfs";
    encrypted = {
      enable = true;
      label = "media2";
      blkDev =
        "/dev/disk/by-uuid/d5f1a797-6655-4ae4-995a-f42dc02f832a"; # UUID for /dev/sda1
      keyFile = "/lukskey";
    };
  };

  # Why does this not work???
  # fileSystems."/media/backup" = {
  #   device =
  #     "/dev/disk/by-uuid/52c6c483-1036-4bc8-b019-1064e6bc5593"; # UUID for /dev/mapper/media2
  #   fsType = "ext4";
  #   options = [ "nofail" "x-systemd.device-timeout=10" ];
  #   encrypted = {
  #     enable = true;
  #     label = "backup";
  #     blkDev =
  #       "/dev/disk/by-uuid/8c4746b9-7ccb-4a94-8e72-502ea6ff4a49"; # UUID for /dev/sda1
  #     keyFile = "/lukskey";
  #   };
  # };

  fileSystems."/media/games" = {
    device = "/dev/disk/by-uuid/0BB20EC37670AE62";
    fsType = "ntfs";
    options = [ "rw" "uid=1000" ];
  };

  fileSystems."/d" = {
    device = "/media/media";
    options = [ "bind" ];
  };

  fileSystems."/f" = {
    device = "/media/media2";
    options = [ "bind" ];
  };

  swapDevices =
    [{ device = "/.swapfile"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}

