# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vfat" "nls_cp437" "nls_iso8859-1" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.luks.yubikeySupport = true;
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
  "nixos-enc" = {
    device = "/dev/sda2";
    preLVM = true; # You may want to set this to false if you need to start a network service first
    yubikey = {
      slot = 2;
      twoFactor = true; # Set to false if you did not set up a user password.
      storage = {
        device = "/dev/sda1";
      };
    };
  }; 
};

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0ce174dc-b00d-4285-ab07-797a67519093";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0ce174dc-b00d-4285-ab07-797a67519093";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F102-2386";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/718617a6-3335-48cf-a7ae-e985664a6e64"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
