[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
# language-server = { command = "vscode-eslint-language-server", args = ["--stdio"], language-id = "typescript" }

# formatter = { command = "prettier_d_slim", args = [
#   "--stdin",
#   "--stdin-filepath files.ts",
# ] }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "bash"
auto-format = true

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "nix"
auto-format = true
formatter = { command = "alejandra" }

[[language]]
name = "hcl"
auto-format = true

[[language]]
name = "scheme"
formatter = { command = "raco", args = ["fmt", "-i"] }
auto-format = true
