[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
# language-server = { command = "vscode-eslint-language-server", args = ["--stdio"], language-id = "typescript" }

# formatter = { command = "prettier_d_slim", args = [
#   "--stdin",
#   "--stdin-filepath files.ts",
# ] }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "bash"
auto-format = true

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "nix"
auto-format = true
formatter = { command = "alejandra" }

[[language]]
name = "hcl"
auto-format = true

[[language]]
name = "templ"
auto-format = true
scope = "source.templ"
injection-regex = "templ"
grammar = "templ"
file-types = ["templ"]
roots = ["go.sum"]
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }
language-servers = ["templ-lsp"]
formatter = { command = "templ", args = ["fmt"] }

[language-server.templ-lsp]
command = "templ"
args = ["lsp"]

[[grammar]]
name = "templ"
source = { git = "https://github.com/vrischmann/tree-sitter-templ", rev = "6ab863186d1ba91718125f59deae6cf68d765fcb" }
