customCommands:
  - key: 't'
    command: "~/code/nixconfig/scripts/helix-open {{.SelectedFile.Name | quote}}"
    context: 'files'
    description: 'open in helix'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never