# espanso configuration file
# backend: Clipboard
backend: Inject
disable_x11_fast_inject: true
undo_backspace: false
# inject_delay: 100
# key_delay: 100
# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/
# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
