#!/usr/bin/env bash

# combines cbz files from japanese folder and english folder
# into the output folder so each 2nd page is the english translation
# assumes the pages and cbz have the same filenames in each language

set -euo pipefail

if [ ! -d japanese ]; then
	echo "No japanese folder found"
	exit 1
fi

if [ ! -d english ]; then
	echo "No english folder found"
	exit 1
fi

if [ ! -d output ]; then
	echo "Creating output folder"
	mkdir output
fi

for jp in japanese/*.cbz; do
	NAME=$(basename "${jp%.*}")
	echo "Processing ${NAME}..."
	en="english/${NAME}.cbz"
	if [ ! -f "$en" ]; then
		echo "Warning: can't find $en"
		continue
	fi
	rm -rf "output/${NAME}"
	rm -rf "output/${NAME}e"
	unzip -j -o -d "output/${NAME}" "${jp}" >/dev/null
	unzip -j -o -d "output/${NAME}e" "${en}" >/dev/null

	for file in output/${NAME}/*; do
		FILENAME=$(basename "${file}")
		EXT="${FILENAME##*.}"
		mv "${file}" "output/${NAME}/${FILENAME%.${EXT}}-1j.${EXT}"
	done

	for file in output/${NAME}e/*; do
		FILENAME=$(basename "${file}")
		EXT="${FILENAME##*.}"
		mv "${file}" "output/${NAME}/${FILENAME%.${EXT}}-2e.${EXT}"
	done
	rm -rf "output/${NAME}e"
	zip -j -r "output/${NAME}.cbz" "output/${NAME}" >/dev/null
	rm -rf "output/${NAME}"
	rm "${jp}"
	rm "${en}"
done
