#!/usr/bin/env bash
set -euo pipefail

sudo systemctl stop k3s
sudo rm -rf /etc/rancher
sudo rm -rf /var/lib/rancher
sudo systemctl start k3s
sudo cat /etc/rancher/k3s/k3s.yaml > ~/.kube/k3s.yaml
export KUBECONFIG=~/.kube/k3s.yaml
