#!/usr/bin/env bash
# search and replace preview across project with sd
set -euo pipefail
IFS=$(echo -en "\n\b")

for file in $(fd --type file); do
  args=( "-p" "$@" "$file" )
  DIFF=$(delta --width $(tput cols) "$file" <(sd "${args[@]}") || true)
  if [[ "$DIFF" != "" ]]; then
    echo "$DIFF"
  fi
done