# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/505c5eb3-4a0a-4e65-9cd4-cd6f5758137d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/6210571b-837c-4354-ae30-90e86b9ae3a2";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/64A6-E37C";
      fsType = "vfat";
    };

  swapDevices = [{ device = "/.swapfile"; }];
  
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
