require 'keymap'
require 'settings'
require 'plugins/autosave'
require 'plugins/barbar'
require 'plugins/cmp'
require 'plugins/comment'
require 'plugins/dap'
require 'plugins/dashboard'
require 'plugins/diffview'
require 'plugins/gitsigns'
require 'plugins/hop'
require 'plugins/indent-blankline'
require 'plugins/lsp'
require 'plugins/lualine'
require 'plugins/luasnip'
require 'plugins/neogit'
require 'plugins/neoscroll'
require 'plugins/nvim-tree'
require 'plugins/rest'
require 'plugins/telescope'
require 'plugins/trouble'
require 'plugins/treesitter'
require 'plugins/neorg' -- requires treesitter
require 'plugins/whichkey'

