# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@types/node-15.0.2" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "15.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-15.0.2.tgz";
        sha512 = "p68+a+KoxpoB47015IeYZYRrdqMUcpbK8re/zpFB8Ld46LHC1lPEbp3EXgkEhAYEcPvjJF6ZO+869SQ0aH1dcA==";
      };
    };
    "@types/unist-2.0.3" = {
      name = "_at_types_slash_unist";
      packageName = "@types/unist";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/unist/-/unist-2.0.3.tgz";
        sha512 = "FvUupuM3rlRsRtCN+fDudtmytGO6iHJuuRKS1Ss0pG5z8oX0diNEw94UEL7hgDbpN94rgaK5R7sWm6RrSkZuAQ==";
      };
    };
    "@types/vfile-3.0.2" = {
      name = "_at_types_slash_vfile";
      packageName = "@types/vfile";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/vfile/-/vfile-3.0.2.tgz";
        sha512 = "b3nLFGaGkJ9rzOcuXRfHkZMdjsawuDD0ENL9fzTophtBg8FJHSGbH7daXkEpcwy3v7Xol3pAvsmlYyFhR4pqJw==";
      };
    };
    "@types/vfile-message-2.0.0" = {
      name = "_at_types_slash_vfile-message";
      packageName = "@types/vfile-message";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/vfile-message/-/vfile-message-2.0.0.tgz";
        sha512 = "GpTIuDpb9u4zIO165fUy9+fXcULdD8HFRNli04GehoMVbeNq7D6OBnqSmg3lxZnC+UvgUhEWKxdKiwYUkGltIw==";
      };
    };
    "array-iterate-1.1.4" = {
      name = "array-iterate";
      packageName = "array-iterate";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-iterate/-/array-iterate-1.1.4.tgz";
        sha512 = "sNRaPGh9nnmdC8Zf+pT3UqP8rnWj5Hf9wiFGsX3wUQ2yVSIhO2ShFwCoceIPpB41QF6i2OEmrHmCo36xronCVA==";
      };
    };
    "bail-1.0.5" = {
      name = "bail";
      packageName = "bail";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/bail/-/bail-1.0.5.tgz";
        sha512 = "xFbRxM1tahm08yHBP16MMjVUAvDaBMD38zsM9EMAUN61omwLmKlOpB/Zku5QkjZ8TZ4vn53pj+t518cH0S03RQ==";
      };
    };
    "character-entities-1.2.4" = {
      name = "character-entities";
      packageName = "character-entities";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities/-/character-entities-1.2.4.tgz";
        sha512 = "iBMyeEHxfVnIakwOuDXpVkc54HijNgCyQB2w0VfGQThle6NXn50zU6V/u+LDhxHcDUPojn6Kpga3PTAD8W1bQw==";
      };
    };
    "character-entities-legacy-1.1.4" = {
      name = "character-entities-legacy";
      packageName = "character-entities-legacy";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities-legacy/-/character-entities-legacy-1.1.4.tgz";
        sha512 = "3Xnr+7ZFS1uxeiUDvV02wQ+QDbc55o97tIV5zHScSPJpcLm/r0DFPcoY3tYRp+VZukxuMeKgXYmsXQHO05zQeA==";
      };
    };
    "character-reference-invalid-1.1.4" = {
      name = "character-reference-invalid";
      packageName = "character-reference-invalid";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-reference-invalid/-/character-reference-invalid-1.1.4.tgz";
        sha512 = "mKKUkUbhPpQlCOfIuZkvSEgktjPFIsZKRRbC6KWVEMvlzblj3i3asQv5ODsrwt0N3pHAEvjP8KTQPHkp0+6jOg==";
      };
    };
    "co-3.1.0" = {
      name = "co";
      packageName = "co";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-3.1.0.tgz";
        sha1 = "4ea54ea5a08938153185e15210c68d9092bc1b78";
      };
    };
    "collapse-white-space-1.0.6" = {
      name = "collapse-white-space";
      packageName = "collapse-white-space";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/collapse-white-space/-/collapse-white-space-1.0.6.tgz";
        sha512 = "jEovNnrhMuqyCcjfEJA56v0Xq8SkIoPKDyaHahwo3POf4qcSXqMYuwNcOTzp74vTsR9Tn08z4MxWqAhcekogkQ==";
      };
    };
    "dictionary-en-gb-2.3.0" = {
      name = "dictionary-en-gb";
      packageName = "dictionary-en-gb";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dictionary-en-gb/-/dictionary-en-gb-2.3.0.tgz";
        sha512 = "P/J2VQp/hDsMTfJhmIYPUBxZqezWuDaUzSgb6oW7JLpUV2So9jCXbR5TaUYXwfO50ZXPYEzQqQHPQK3pKcs7Rg==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "irregular-plurals-2.0.0" = {
      name = "irregular-plurals";
      packageName = "irregular-plurals";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/irregular-plurals/-/irregular-plurals-2.0.0.tgz";
        sha512 = "Y75zBYLkh0lJ9qxeHlMjQ7bSbyiSqNW/UOPWDmzC7cXskL1hekSITh1Oc6JV0XCWWZ9DE8VYSB71xocLk3gmGw==";
      };
    };
    "is-alphabetical-1.0.4" = {
      name = "is-alphabetical";
      packageName = "is-alphabetical";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-alphabetical/-/is-alphabetical-1.0.4.tgz";
        sha512 = "DwzsA04LQ10FHTZuL0/grVDk4rFoVH1pjAToYwBrHSxcrBIGQuXrQMtD5U1b0U2XVgKZCTLLP8u2Qxqhy3l2Vg==";
      };
    };
    "is-alphanumerical-1.0.4" = {
      name = "is-alphanumerical";
      packageName = "is-alphanumerical";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-alphanumerical/-/is-alphanumerical-1.0.4.tgz";
        sha512 = "UzoZUr+XfVz3t3v4KyGEniVL9BDRoQtY7tOyrRybkVNjDFWyo1yhXNGrrBTQxp3ib9BLAWs7k2YKBQsFRkZG9A==";
      };
    };
    "is-buffer-2.0.5" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-2.0.5.tgz";
        sha512 = "i2R6zNFDwgEHJyQUtJEk0XFi1i0dPFn/oqjK3/vPCcDeJvW5NQ83V8QbicfF1SupOaB0h8ntgBC2YiE7dfyctQ==";
      };
    };
    "is-decimal-1.0.4" = {
      name = "is-decimal";
      packageName = "is-decimal";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-decimal/-/is-decimal-1.0.4.tgz";
        sha512 = "RGdriMmQQvZ2aqaQq3awNA6dCGtKpiDFcOzrTWrDAT2MiWrKQVPmxLGHl7Y2nNu6led0kEyoX0enY0qXYsv9zw==";
      };
    };
    "is-hexadecimal-1.0.4" = {
      name = "is-hexadecimal";
      packageName = "is-hexadecimal";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-hexadecimal/-/is-hexadecimal-1.0.4.tgz";
        sha512 = "gyPJuv83bHMpocVYoqof5VDiZveEoGoFL8m3BXNb2VW8Xs+rz9kqO8LOQ5DH6EsuvilT1ApazU0pyl+ytbPtlw==";
      };
    };
    "is-plain-obj-1.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-1.1.0.tgz";
        sha1 = "71a50c8429dfca773c92a390a4a03b39fcd51d3e";
      };
    };
    "is-whitespace-character-1.0.4" = {
      name = "is-whitespace-character";
      packageName = "is-whitespace-character";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-whitespace-character/-/is-whitespace-character-1.0.4.tgz";
        sha512 = "SDweEzfIZM0SJV0EUga669UTKlmL0Pq8Lno0QDQsPnvECB3IM2aP0gdx5TrU0A01MAPfViaZiI2V1QMZLaKK5w==";
      };
    };
    "is-word-character-1.0.4" = {
      name = "is-word-character";
      packageName = "is-word-character";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-word-character/-/is-word-character-1.0.4.tgz";
        sha512 = "5SMO8RVennx3nZrqtKwCGyyetPE9VDba5ugvKLaD4KopPG5kR4mQ7tNt/r7feL5yt5h3lpuBbIUmCOG2eSzXHA==";
      };
    };
    "lodash.includes-4.3.0" = {
      name = "lodash.includes";
      packageName = "lodash.includes";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.includes/-/lodash.includes-4.3.0.tgz";
        sha1 = "60bb98a87cb923c68ca1e51325483314849f553f";
      };
    };
    "markdown-escapes-1.0.4" = {
      name = "markdown-escapes";
      packageName = "markdown-escapes";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-escapes/-/markdown-escapes-1.0.4.tgz";
        sha512 = "8z4efJYk43E0upd0NbVXwgSTQs6cT3T06etieCMEg7dRbzCbxUCK/GHlX8mhHRDcp+OLlHkPKsvqQTCvsRl2cg==";
      };
    };
    "mdast-comment-marker-1.1.2" = {
      name = "mdast-comment-marker";
      packageName = "mdast-comment-marker";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-comment-marker/-/mdast-comment-marker-1.1.2.tgz";
        sha512 = "vTFXtmbbF3rgnTh3Zl3irso4LtvwUq/jaDvT2D1JqTGAwaipcS7RpTxzi6KjoRqI9n2yuAhzLDAC8xVTF3XYVQ==";
      };
    };
    "mdast-util-heading-style-1.0.6" = {
      name = "mdast-util-heading-style";
      packageName = "mdast-util-heading-style";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-heading-style/-/mdast-util-heading-style-1.0.6.tgz";
        sha512 = "8ZuuegRqS0KESgjAGW8zTx4tJ3VNIiIaGFNEzFpRSAQBavVc7AvOo9I4g3crcZBfYisHs4seYh0rAVimO6HyOw==";
      };
    };
    "mdast-util-to-nlcst-3.2.3" = {
      name = "mdast-util-to-nlcst";
      packageName = "mdast-util-to-nlcst";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-nlcst/-/mdast-util-to-nlcst-3.2.3.tgz";
        sha512 = "hPIsgEg7zCvdU6/qvjcR6lCmJeRuIEpZGY5xBV+pqzuMOvQajyyF8b6f24f8k3Rw8u40GwkI3aAxUXr3bB2xag==";
      };
    };
    "mdast-util-to-string-1.1.0" = {
      name = "mdast-util-to-string";
      packageName = "mdast-util-to-string";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-string/-/mdast-util-to-string-1.1.0.tgz";
        sha512 = "jVU0Nr2B9X3MU4tSK7JP1CMkSvOj7X5l/GboG1tKRw52lLF1x2Ju92Ms9tNetCcbfX3hzlM73zYo2NKkWSfF/A==";
      };
    };
    "nlcst-is-literal-1.2.2" = {
      name = "nlcst-is-literal";
      packageName = "nlcst-is-literal";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nlcst-is-literal/-/nlcst-is-literal-1.2.2.tgz";
        sha512 = "R+1OJEmRl3ZOp9d8PbiRxGpnvmpi3jU+lzSqCJoLeogdEh0FYDRH1aC223qUbaKffxNTJkEfeDOeQfziw749yA==";
      };
    };
    "nlcst-to-string-2.0.4" = {
      name = "nlcst-to-string";
      packageName = "nlcst-to-string";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/nlcst-to-string/-/nlcst-to-string-2.0.4.tgz";
        sha512 = "3x3jwTd6UPG7vi5k4GEzvxJ5rDA7hVUIRNHPblKuMVP9Z3xmlsd9cgLcpAMkc5uPOBna82EeshROFhsPkbnTZg==";
      };
    };
    "nspell-2.1.5" = {
      name = "nspell";
      packageName = "nspell";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/nspell/-/nspell-2.1.5.tgz";
        sha512 = "PSStyugKMiD9mHmqI/CR5xXrSIGejUXPlo88FBRq5Og1kO5QwQ5Ilu8D8O5I/SHpoS+mibpw6uKA8rd3vXd2Sg==";
      };
    };
    "parse-english-4.2.0" = {
      name = "parse-english";
      packageName = "parse-english";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-english/-/parse-english-4.2.0.tgz";
        sha512 = "jw5N6wZUZViIw3VLG/FUSeL3vDhfw5Q2g4E3nYC69Mm5ANbh9ZWd+eligQbeUoyObZM8neynTn3l14e09pjEWg==";
      };
    };
    "parse-entities-1.2.2" = {
      name = "parse-entities";
      packageName = "parse-entities";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-entities/-/parse-entities-1.2.2.tgz";
        sha512 = "NzfpbxW/NPrzZ/yYSoQxyqUZMZXIdCfE0OIN4ESsnptHJECoUk3FZktxNuzQf4tjt5UEopnxpYJbvYuxIFDdsg==";
      };
    };
    "parse-latin-4.3.0" = {
      name = "parse-latin";
      packageName = "parse-latin";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-latin/-/parse-latin-4.3.0.tgz";
        sha512 = "TYKL+K98dcAWoCw/Ac1yrPviU8Trk+/gmjQVaoWEFDZmVD4KRg6c/80xKqNNFQObo2mTONgF8trzAf2UTwKafw==";
      };
    };
    "plur-3.1.1" = {
      name = "plur";
      packageName = "plur";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/plur/-/plur-3.1.1.tgz";
        sha512 = "t1Ax8KUvV3FFII8ltczPn2tJdjqbd1sIzu6t4JL7nQ3EyeL/lTrj5PWKb06ic5/6XYDr65rQ4uzQEGN70/6X5w==";
      };
    };
    "quotation-1.1.3" = {
      name = "quotation";
      packageName = "quotation";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/quotation/-/quotation-1.1.3.tgz";
        sha512 = "45gUgmX/RtQOQV1kwM06boP49OYXcKCPrYwdmAvs5YqkpiobhNKKwo524JM6Ma0ko3oN9tXNcWs9+ABq3Ry7YA==";
      };
    };
    "remark-lint-6.0.6" = {
      name = "remark-lint";
      packageName = "remark-lint";
      version = "6.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint/-/remark-lint-6.0.6.tgz";
        sha512 = "JBY6zz5fYQFN724Vq6VeiHwhyjVIlrww/dE1+hWGcDyUuz7YNCqwZKwBdQGDvslICkzHw/wEExNEb8D4PNiLlA==";
      };
    };
    "remark-lint-blockquote-indentation-1.0.4" = {
      name = "remark-lint-blockquote-indentation";
      packageName = "remark-lint-blockquote-indentation";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-blockquote-indentation/-/remark-lint-blockquote-indentation-1.0.4.tgz";
        sha512 = "ExcDP7lufshEBNkVddSHa+Bz/97PtFstIniQ8ZF2TahHPmpx92z3mkI/nXL2Qt5d3B09eTVvh4Pvhgp6x2470g==";
      };
    };
    "remark-lint-code-block-style-1.0.4" = {
      name = "remark-lint-code-block-style";
      packageName = "remark-lint-code-block-style";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-code-block-style/-/remark-lint-code-block-style-1.0.4.tgz";
        sha512 = "Wq5F94nkaWTx8W/9C/ydG+DhVWLirBrWb0xnoMQ0cHnizAd3BWw8g0x5L7yglMYSUSVLWY0jfMHgOe9UW3JfTw==";
      };
    };
    "remark-lint-definition-case-1.0.5" = {
      name = "remark-lint-definition-case";
      packageName = "remark-lint-definition-case";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-definition-case/-/remark-lint-definition-case-1.0.5.tgz";
        sha512 = "iirq74fKhJZsFw7x4FJuLVRkXclntutG1YKajfLaE3Gm14YlJWBEoabNTk+ENR4QXoB9rTdEqn3Cc3ImO8qciQ==";
      };
    };
    "remark-lint-definition-spacing-1.0.5" = {
      name = "remark-lint-definition-spacing";
      packageName = "remark-lint-definition-spacing";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-definition-spacing/-/remark-lint-definition-spacing-1.0.5.tgz";
        sha512 = "ss8OQmK4c/1amEAJpDjkFiByLyXpsYFNzmk6rEZQkxZZd+DVHI0oF+CzSeMVHu48rF2qHOkKhVghqrCM0vleAA==";
      };
    };
    "remark-lint-emphasis-marker-1.0.4" = {
      name = "remark-lint-emphasis-marker";
      packageName = "remark-lint-emphasis-marker";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-emphasis-marker/-/remark-lint-emphasis-marker-1.0.4.tgz";
        sha512 = "TdYISSw7Ib6EJDApDj9zcZNDCJEaEoQIrYS3+QH2TQxoDx96B0t1bbErRM5L/hx1UWPBpeFLKpgIWL163eMmYA==";
      };
    };
    "remark-lint-fenced-code-flag-1.0.4" = {
      name = "remark-lint-fenced-code-flag";
      packageName = "remark-lint-fenced-code-flag";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-fenced-code-flag/-/remark-lint-fenced-code-flag-1.0.4.tgz";
        sha512 = "bkQvlEYco6ZzdzvGPrY7DBsqSq/2mZEmdhpn0KdMEZ9kcKJP4unQdVQys04SKnf9QISqQ446VnQj5Q4E3HMSkQ==";
      };
    };
    "remark-lint-fenced-code-marker-1.0.4" = {
      name = "remark-lint-fenced-code-marker";
      packageName = "remark-lint-fenced-code-marker";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-fenced-code-marker/-/remark-lint-fenced-code-marker-1.0.4.tgz";
        sha512 = "aJF4ISIEvK3NX+C2rN93QoS/32SSiytQKRSeGa+HwsAn3sTwqmy2IoAwbFeZIZA2vqKcVB4h1b9yKamSlfX30Q==";
      };
    };
    "remark-lint-file-extension-1.0.5" = {
      name = "remark-lint-file-extension";
      packageName = "remark-lint-file-extension";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-file-extension/-/remark-lint-file-extension-1.0.5.tgz";
        sha512 = "oVQdf5vEomwHkfQ7R/mgmsWW2H/t9kSvnrxtVoNOHr+qnOEafKKDn+AFhioN2kqtjCZBAjSSrePs6xGKmXKDTw==";
      };
    };
    "remark-lint-final-definition-1.0.4" = {
      name = "remark-lint-final-definition";
      packageName = "remark-lint-final-definition";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-final-definition/-/remark-lint-final-definition-1.0.4.tgz";
        sha512 = "y9aDZPhqWcI7AtrJtL69HE6MoWMqDqLQUyWMadzAYUYb9/m4ciLdygJ4cWVpEN3n4mkBepHIsWzASaKHHBDJOQ==";
      };
    };
    "remark-lint-hard-break-spaces-1.0.5" = {
      name = "remark-lint-hard-break-spaces";
      packageName = "remark-lint-hard-break-spaces";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-hard-break-spaces/-/remark-lint-hard-break-spaces-1.0.5.tgz";
        sha512 = "Rss7ujNtxipO/hasWYc0QdiO8D5VyliSwj3zAZ8GeDn0ix2KH+pY4/AJC7i9IGcVVbUGvvXLpJB3Pp1VeY7oKw==";
      };
    };
    "remark-lint-heading-increment-1.0.4" = {
      name = "remark-lint-heading-increment";
      packageName = "remark-lint-heading-increment";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-heading-increment/-/remark-lint-heading-increment-1.0.4.tgz";
        sha512 = "3PJj32G7W1OUyRVSZiZbSOxyFAsw/mNssIosS9G8+6Lq2yeTSMDoCJy0+LC+s00nORFcbzeMedMK5U/eLbDe4w==";
      };
    };
    "remark-lint-heading-style-1.0.4" = {
      name = "remark-lint-heading-style";
      packageName = "remark-lint-heading-style";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-heading-style/-/remark-lint-heading-style-1.0.4.tgz";
        sha512 = "ASssbw0vj9urTMxDJGpOn4K7d9MgPQPJGaCD+7v7je42krofvqC4CxpYvO/fOAkRZcttE91VfFHxkaPjiBtQLw==";
      };
    };
    "remark-lint-link-title-style-1.0.5" = {
      name = "remark-lint-link-title-style";
      packageName = "remark-lint-link-title-style";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-link-title-style/-/remark-lint-link-title-style-1.0.5.tgz";
        sha512 = "Nu0cKj220q/PmUzELhYRUR2uxXabWuFJq9sApkgsc59uh+NKDtCEdpxkx7Zwvn6kUEwpuQVimeRfdesiKxX52g==";
      };
    };
    "remark-lint-list-item-content-indent-1.0.4" = {
      name = "remark-lint-list-item-content-indent";
      packageName = "remark-lint-list-item-content-indent";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-list-item-content-indent/-/remark-lint-list-item-content-indent-1.0.4.tgz";
        sha512 = "zfEeAayZjEKkPr07fnhkGLENxOhnm0WZJTj6UBIXhtGu7rX23WNKSZaiou8iUoHxcO6ySCvIUJAEmq/XN1FxkQ==";
      };
    };
    "remark-lint-list-item-indent-1.0.5" = {
      name = "remark-lint-list-item-indent";
      packageName = "remark-lint-list-item-indent";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-list-item-indent/-/remark-lint-list-item-indent-1.0.5.tgz";
        sha512 = "DjRgxjqaVMrnlQFJypizTPtLa9gSM5ad0LVIFDSstV2UVXSgpBi2+bSsFJEXb4Fkjo/d2JAgt27UhzhcoF2lnw==";
      };
    };
    "remark-lint-list-item-spacing-1.1.4" = {
      name = "remark-lint-list-item-spacing";
      packageName = "remark-lint-list-item-spacing";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-list-item-spacing/-/remark-lint-list-item-spacing-1.1.4.tgz";
        sha512 = "zZELzTPYCoOCnOWh/nYTfQWnGXWg4/I5KpwrjBqe7WYwoMtvLVU9mqjRj2jHEbmirEXas54NZnYnkCoIBMS4bw==";
      };
    };
    "remark-lint-maximum-heading-length-1.0.4" = {
      name = "remark-lint-maximum-heading-length";
      packageName = "remark-lint-maximum-heading-length";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-maximum-heading-length/-/remark-lint-maximum-heading-length-1.0.4.tgz";
        sha512 = "dhDBnUFXMuHoW8LSV/VICJAJO+wWumnvuu3ND7MJquCYrsjX2vcRmJXL5cusJSY4yqPosKlOowIkzdV5B6/SDQ==";
      };
    };
    "remark-lint-maximum-line-length-1.2.2" = {
      name = "remark-lint-maximum-line-length";
      packageName = "remark-lint-maximum-line-length";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-maximum-line-length/-/remark-lint-maximum-line-length-1.2.2.tgz";
        sha512 = "ItAdjK+tUhqggqFvtAJ8iJ0MbBgShLl0HDgpG3In0QSYp/dmofO77DjvRjCJQo1pQYS8/LwlBii9cqg/3MwFfA==";
      };
    };
    "remark-lint-no-auto-link-without-protocol-1.0.4" = {
      name = "remark-lint-no-auto-link-without-protocol";
      packageName = "remark-lint-no-auto-link-without-protocol";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-auto-link-without-protocol/-/remark-lint-no-auto-link-without-protocol-1.0.4.tgz";
        sha512 = "dhDHQLeaI79p7SRoKfxJ9c8J5otQsGua7ILeNbs2Onzn46/tp9ir6zjq3Lfh4VJJr4OVign2e8u+MzXsS7Uu/A==";
      };
    };
    "remark-lint-no-blockquote-without-marker-2.0.4" = {
      name = "remark-lint-no-blockquote-without-marker";
      packageName = "remark-lint-no-blockquote-without-marker";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-blockquote-without-marker/-/remark-lint-no-blockquote-without-marker-2.0.4.tgz";
        sha512 = "a5LFGj7It2z7aBRGaAcztk4D2pax2b7dK9iOarIWv/JBus/PSjZJxzZCma2aAAOQhv3wbNTwqQwuQC0UJHMbPg==";
      };
    };
    "remark-lint-no-consecutive-blank-lines-1.0.4" = {
      name = "remark-lint-no-consecutive-blank-lines";
      packageName = "remark-lint-no-consecutive-blank-lines";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-consecutive-blank-lines/-/remark-lint-no-consecutive-blank-lines-1.0.4.tgz";
        sha512 = "33rYrp+3OQ2UjG2/xhctruCvkP2iKLuHJhoUOAUV3BGwqJjAB+xNOl+0DdvDo0fxh5dyZuNesBuos3xr2yVR+w==";
      };
    };
    "remark-lint-no-duplicate-headings-1.0.5" = {
      name = "remark-lint-no-duplicate-headings";
      packageName = "remark-lint-no-duplicate-headings";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-duplicate-headings/-/remark-lint-no-duplicate-headings-1.0.5.tgz";
        sha512 = "4GKPxhKpN797V/6Jg1K4Zwqq+PhsjC633+wQMrZcTvOJfY+Rq1i7sNJ9lJVZnsDAlZJI56VqZCKnPJmS2br87g==";
      };
    };
    "remark-lint-no-emphasis-as-heading-1.0.4" = {
      name = "remark-lint-no-emphasis-as-heading";
      packageName = "remark-lint-no-emphasis-as-heading";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-emphasis-as-heading/-/remark-lint-no-emphasis-as-heading-1.0.4.tgz";
        sha512 = "gnsInLxTkc59eVD3/qelFagD/NcrMPKXT1sy7i4e8D2jqQyrIHHl0p3TfiyNNt8qIjKMKhlIii4k4kVk/3Mczg==";
      };
    };
    "remark-lint-no-file-name-articles-1.0.5" = {
      name = "remark-lint-no-file-name-articles";
      packageName = "remark-lint-no-file-name-articles";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-file-name-articles/-/remark-lint-no-file-name-articles-1.0.5.tgz";
        sha512 = "AQk5eTb3s3TAPPjiglZgqlQj4ycao+gPs8/XkdN1VCPUtewW0GgwoQe7YEuBKayJ6ioN8dGP37Kg/P/PlKaRQA==";
      };
    };
    "remark-lint-no-file-name-consecutive-dashes-1.0.5" = {
      name = "remark-lint-no-file-name-consecutive-dashes";
      packageName = "remark-lint-no-file-name-consecutive-dashes";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-file-name-consecutive-dashes/-/remark-lint-no-file-name-consecutive-dashes-1.0.5.tgz";
        sha512 = "Mg2IDsi790/dSdAzwnBnsMYdZm3qC2QgGwqOWcr0TPABJhhjC3p8r5fX4MNMTXI5It7B7bW9+ImmCeLOZiXkLg==";
      };
    };
    "remark-lint-no-file-name-irregular-characters-1.0.5" = {
      name = "remark-lint-no-file-name-irregular-characters";
      packageName = "remark-lint-no-file-name-irregular-characters";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-file-name-irregular-characters/-/remark-lint-no-file-name-irregular-characters-1.0.5.tgz";
        sha512 = "Oe5i99qNUKc2bxmiH421o5B/kqlf1dfjAxpHNLhi2X2dXE91zRGavrlRM/4f4oR0N9Bqb3qB9JZPyMPWrzu9XA==";
      };
    };
    "remark-lint-no-file-name-mixed-case-1.0.5" = {
      name = "remark-lint-no-file-name-mixed-case";
      packageName = "remark-lint-no-file-name-mixed-case";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-file-name-mixed-case/-/remark-lint-no-file-name-mixed-case-1.0.5.tgz";
        sha512 = "ilrUCbHZin/ENwr8c3SC2chgkFsizXjBQIB/oZ7gnm1IkCkZPiMyXZAHdpwC/DjbrpGxfMYh9JmIHao4giS5+A==";
      };
    };
    "remark-lint-no-file-name-outer-dashes-1.0.6" = {
      name = "remark-lint-no-file-name-outer-dashes";
      packageName = "remark-lint-no-file-name-outer-dashes";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-file-name-outer-dashes/-/remark-lint-no-file-name-outer-dashes-1.0.6.tgz";
        sha512 = "rT8CmcIlenegS0Yst4maYXdZfqIjBOiRUY8j/KJkORF5tKH+3O1/S07025qPGmcRihzK3w4yO0K8rgkKQw0b9w==";
      };
    };
    "remark-lint-no-heading-punctuation-1.0.4" = {
      name = "remark-lint-no-heading-punctuation";
      packageName = "remark-lint-no-heading-punctuation";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-heading-punctuation/-/remark-lint-no-heading-punctuation-1.0.4.tgz";
        sha512 = "++/HXg/qtVssJjzq2ZgEreoxaazw9KkYrAbTDImKV7Fypo+7bZFELUvFicq0/i9qwAwt1tvhkKtLYt1W/sr1JQ==";
      };
    };
    "remark-lint-no-inline-padding-1.0.5" = {
      name = "remark-lint-no-inline-padding";
      packageName = "remark-lint-no-inline-padding";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-inline-padding/-/remark-lint-no-inline-padding-1.0.5.tgz";
        sha512 = "AjS34hBRasYiIAKZJ7/9U42LouRHok2WVTRdQPcVtRBswStNOuot59S+FRsatqlk1wvMmjytqxUKQfVTSeu9ag==";
      };
    };
    "remark-lint-no-literal-urls-1.0.4" = {
      name = "remark-lint-no-literal-urls";
      packageName = "remark-lint-no-literal-urls";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-literal-urls/-/remark-lint-no-literal-urls-1.0.4.tgz";
        sha512 = "sHjbzaSG4z6jMu1L0Qx1b7VvIQHy0bR4xZ6t9auJ5AoB5ua8hb/970s77irH1+46TF1ezhE7i+QDjmhcQi09xg==";
      };
    };
    "remark-lint-no-multiple-toplevel-headings-1.0.5" = {
      name = "remark-lint-no-multiple-toplevel-headings";
      packageName = "remark-lint-no-multiple-toplevel-headings";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-multiple-toplevel-headings/-/remark-lint-no-multiple-toplevel-headings-1.0.5.tgz";
        sha512 = "RZ1YPxRO7Bo8mT+A36cZ7nx2QHFAKk+oE6j87YrZYpAKr2oF6snKS8nIGhVku4PSI/9cW1G12MZz1cAA5rcjFw==";
      };
    };
    "remark-lint-no-shell-dollars-1.0.4" = {
      name = "remark-lint-no-shell-dollars";
      packageName = "remark-lint-no-shell-dollars";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-shell-dollars/-/remark-lint-no-shell-dollars-1.0.4.tgz";
        sha512 = "YXFj8FUVTKkVvoAbFY3zv1Ol7Kj1i+qdze3pXSgRG61y1LpfL8/HpnvFrseMbBmNw6o4WpjTo7GoArngJ1sCeg==";
      };
    };
    "remark-lint-no-shortcut-reference-image-1.0.4" = {
      name = "remark-lint-no-shortcut-reference-image";
      packageName = "remark-lint-no-shortcut-reference-image";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-shortcut-reference-image/-/remark-lint-no-shortcut-reference-image-1.0.4.tgz";
        sha512 = "5/9QoesnOHIDwMHU9x+AGPBiFoMe9ZBKIR8nC17C6ZdksgwUIpjBJ3VX5POFlt5E6OhAZaeXqUCq9G2USccEdA==";
      };
    };
    "remark-lint-no-shortcut-reference-link-1.0.5" = {
      name = "remark-lint-no-shortcut-reference-link";
      packageName = "remark-lint-no-shortcut-reference-link";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-shortcut-reference-link/-/remark-lint-no-shortcut-reference-link-1.0.5.tgz";
        sha512 = "qDVL7/0ptOTd/nyd9u/4MYFWQtYQU8povdUB45UgTXy5Rrf1WsC+4DfzAEZkX3tOSTExdAIf1WOKqdC5xRcfvA==";
      };
    };
    "remark-lint-no-table-indentation-1.0.5" = {
      name = "remark-lint-no-table-indentation";
      packageName = "remark-lint-no-table-indentation";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-no-table-indentation/-/remark-lint-no-table-indentation-1.0.5.tgz";
        sha512 = "eE1GL+IzU3vtHdYCKHCZEIhCwiwCM7UH+pMDIMpGfH2LB3cB/Nrfbiz9xadGkARKqxxDMsJSBZDw4A/01IU+kA==";
      };
    };
    "remark-lint-ordered-list-marker-style-1.0.4" = {
      name = "remark-lint-ordered-list-marker-style";
      packageName = "remark-lint-ordered-list-marker-style";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-ordered-list-marker-style/-/remark-lint-ordered-list-marker-style-1.0.4.tgz";
        sha512 = "c6AIqeePzm3nfkPCbTdwBS3/AQICgwE76+ryOc7tsSq4ulyK/Nt8Syvi/oiHYuonBddZoGtFTNCn0jqen9qscA==";
      };
    };
    "remark-lint-ordered-list-marker-value-1.0.5" = {
      name = "remark-lint-ordered-list-marker-value";
      packageName = "remark-lint-ordered-list-marker-value";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-ordered-list-marker-value/-/remark-lint-ordered-list-marker-value-1.0.5.tgz";
        sha512 = "eKepbNNfu9rEuG8WvV0sc7B+KiPMgq5Nc9baAxL9Hi6mhpj347YFWXxJUNttSINS13YTpnHxPvXmF9SzhjFKNQ==";
      };
    };
    "remark-lint-rule-style-1.0.4" = {
      name = "remark-lint-rule-style";
      packageName = "remark-lint-rule-style";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-rule-style/-/remark-lint-rule-style-1.0.4.tgz";
        sha512 = "omr5P6CCvo2zixCzK9uiGZpwzOE+4rc+95kWH95k2iA6Rp8Qohp8RK4unSRKLtFYGUhSbiQPgWaQXHDxMkWczg==";
      };
    };
    "remark-lint-strong-marker-1.0.4" = {
      name = "remark-lint-strong-marker";
      packageName = "remark-lint-strong-marker";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-strong-marker/-/remark-lint-strong-marker-1.0.4.tgz";
        sha512 = "X9f6yhZ85cdP0cmCgkqlbxllpeQ60pS9Qqk9Jb9SZo6f95esaHptQ5bExb1ZVXzhSHz2Xz86tUhXtzG3zGFD4g==";
      };
    };
    "remark-lint-table-cell-padding-1.0.5" = {
      name = "remark-lint-table-cell-padding";
      packageName = "remark-lint-table-cell-padding";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-table-cell-padding/-/remark-lint-table-cell-padding-1.0.5.tgz";
        sha512 = "N/WpcymrGBSPbLiv2OQTvdzNn6H9ctdyEA+P/odn4G9FqyrLmeTMkGJuGtinU569hLG/RtHqZIDeFVDiYi8Wzw==";
      };
    };
    "remark-lint-table-pipe-alignment-1.0.4" = {
      name = "remark-lint-table-pipe-alignment";
      packageName = "remark-lint-table-pipe-alignment";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-table-pipe-alignment/-/remark-lint-table-pipe-alignment-1.0.4.tgz";
        sha512 = "pmELEOXeUjMQedyVvOtZcTCnTu6FxZ4gfBskMx6iJhOFEEKTFOmviqlKLpndPBxFNZB86AiE0C00/NvAaut8dw==";
      };
    };
    "remark-lint-table-pipes-1.0.4" = {
      name = "remark-lint-table-pipes";
      packageName = "remark-lint-table-pipes";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-table-pipes/-/remark-lint-table-pipes-1.0.4.tgz";
        sha512 = "0fdnoiiSLIPd/76gNvQY4pg27d8HkMmmv5gCGfD+Z/Si9DdpbJdq93U0kX+Botb3+/4VEDIlcU7Cp5HXppMTWA==";
      };
    };
    "remark-lint-unordered-list-marker-style-1.0.4" = {
      name = "remark-lint-unordered-list-marker-style";
      packageName = "remark-lint-unordered-list-marker-style";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-lint-unordered-list-marker-style/-/remark-lint-unordered-list-marker-style-1.0.4.tgz";
        sha512 = "lcuG1J74VGTT4gl8oH33HpkHrqorxjxMlJnBupLFrVowqvJ2hAq8yPJdGZ7P46uZOYw+Xz+Qv08bF8A73PNWxQ==";
      };
    };
    "remark-message-control-4.2.0" = {
      name = "remark-message-control";
      packageName = "remark-message-control";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-message-control/-/remark-message-control-4.2.0.tgz";
        sha512 = "WXH2t5ljTyhsXlK1zPBLF3iPHbXl58R94phPMreS1xcHWBZJt6Oiu8RtNjy1poZFb3PqKnbYLJeR/CWcZ1bTFw==";
      };
    };
    "remark-parse-6.0.3" = {
      name = "remark-parse";
      packageName = "remark-parse";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-parse/-/remark-parse-6.0.3.tgz";
        sha512 = "QbDXWN4HfKTUC0hHa4teU463KclLAnwpn/FBn87j9cKYJWWawbiLgMfP2Q4XwhxxuuuOxHlw+pSN0OKuJwyVvg==";
      };
    };
    "remark-preset-lint-markdown-style-guide-2.1.4" = {
      name = "remark-preset-lint-markdown-style-guide";
      packageName = "remark-preset-lint-markdown-style-guide";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-preset-lint-markdown-style-guide/-/remark-preset-lint-markdown-style-guide-2.1.4.tgz";
        sha512 = "CGEN3DRtJEp+BvfgZ+VKxuq0Ij8Uw2DXfrbhK2xn4/XxatcHRPN8tnagXbMe1LHaQJGN8Gl1+UyLjsfIk6hyGQ==";
      };
    };
    "remark-retext-3.1.3" = {
      name = "remark-retext";
      packageName = "remark-retext";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-retext/-/remark-retext-3.1.3.tgz";
        sha512 = "UujXAm28u4lnUvtOZQFYfRIhxX+auKI9PuA2QpQVTT7gYk1OgX6o0OUrSo1KOa6GNrFX+OODOtS5PWIHPxM7qw==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "replace-ext-1.0.0" = {
      name = "replace-ext";
      packageName = "replace-ext";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/replace-ext/-/replace-ext-1.0.0.tgz";
        sha1 = "de63128373fcbf7c3ccfa4de5a480c45a67958eb";
      };
    };
    "retext-6.0.2" = {
      name = "retext";
      packageName = "retext";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/retext/-/retext-6.0.2.tgz";
        sha512 = "CxpBywVxRjzikCRrC6Z87KzqzuSbCDLLqpQSzjzE0xlzPaZemZiywCHEzX7eSWRdXY5006rYgD7Zm4BCyzFxvg==";
      };
    };
    "retext-english-3.0.4" = {
      name = "retext-english";
      packageName = "retext-english";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/retext-english/-/retext-english-3.0.4.tgz";
        sha512 = "yr1PgaBDde+25aJXrnt3p1jvT8FVLVat2Bx8XeAWX13KXo8OT+3nWGU3HWxM4YFJvmfqvJYJZG2d7xxaO774gw==";
      };
    };
    "retext-latin-2.0.4" = {
      name = "retext-latin";
      packageName = "retext-latin";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/retext-latin/-/retext-latin-2.0.4.tgz";
        sha512 = "fOoSSoQgDZ+l/uS81oxI3alBghDUPja0JEl0TpQxI6MN+dhM6fLFumPJwMZ4PJTyL5FFAgjlsdv8IX+6IRuwMw==";
      };
    };
    "retext-spell-2.4.1" = {
      name = "retext-spell";
      packageName = "retext-spell";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/retext-spell/-/retext-spell-2.4.1.tgz";
        sha512 = "l2C37Sz+JMLgUJHqqNA2bV3Qqh7V6zWT3fCi8MtsZn2PoanDh57Tz2NW/DJpoEIsK9mV7o2EMvQmIMt5cgcgAg==";
      };
    };
    "retext-stringify-2.0.4" = {
      name = "retext-stringify";
      packageName = "retext-stringify";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/retext-stringify/-/retext-stringify-2.0.4.tgz";
        sha512 = "xOtx5mFJBoT3j7PBtiY2I+mEGERNniofWktI1cKXvjMEJPOuqve0dghLHO1+gz/gScLn4zqspDGv4kk2wS5kSA==";
      };
    };
    "sliced-1.0.1" = {
      name = "sliced";
      packageName = "sliced";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sliced/-/sliced-1.0.1.tgz";
        sha1 = "0b3a662b5d04c3177b1926bea82b03f837a2ef41";
      };
    };
    "state-toggle-1.0.3" = {
      name = "state-toggle";
      packageName = "state-toggle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/state-toggle/-/state-toggle-1.0.3.tgz";
        sha512 = "d/5Z4/2iiCnHw6Xzghyhb+GcmF89bxwgXG60wjIiZaxnymbyOmI8Hk4VqHXiVVp6u2ysaskFfXg3ekCj4WNftQ==";
      };
    };
    "trim-0.0.1" = {
      name = "trim";
      packageName = "trim";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim/-/trim-0.0.1.tgz";
        sha1 = "5858547f6b290757ee95cccc666fb50084c460dd";
      };
    };
    "trim-trailing-lines-1.1.4" = {
      name = "trim-trailing-lines";
      packageName = "trim-trailing-lines";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim-trailing-lines/-/trim-trailing-lines-1.1.4.tgz";
        sha512 = "rjUWSqnfTNrjbB9NQWfPMH/xRK1deHeGsHoVfpxJ++XeYXE0d6B1En37AHfw3jtfTU7dzMzZL2jjpe8Qb5gLIQ==";
      };
    };
    "trough-1.0.5" = {
      name = "trough";
      packageName = "trough";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/trough/-/trough-1.0.5.tgz";
        sha512 = "rvuRbTarPXmMb79SmzEp8aqXNKcK+y0XaB298IXueQ8I2PsrATcPBCSPyK/dDNa2iWOhKlfNnOjdAOTBU/nkFA==";
      };
    };
    "unherit-1.1.3" = {
      name = "unherit";
      packageName = "unherit";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/unherit/-/unherit-1.1.3.tgz";
        sha512 = "Ft16BJcnapDKp0+J/rqFC3Rrk6Y/Ng4nzsC028k2jdDII/rdZ7Wd3pPT/6+vIIxRagwRc9K0IUX0Ra4fKvw+WQ==";
      };
    };
    "unified-7.1.0" = {
      name = "unified";
      packageName = "unified";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unified/-/unified-7.1.0.tgz";
        sha512 = "lbk82UOIGuCEsZhPj8rNAkXSDXd6p0QLzIuSsCdxrqnqU56St4eyOB+AlXsVgVeRmetPTYydIuvFfpDIed8mqw==";
      };
    };
    "unified-lint-rule-1.0.6" = {
      name = "unified-lint-rule";
      packageName = "unified-lint-rule";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/unified-lint-rule/-/unified-lint-rule-1.0.6.tgz";
        sha512 = "YPK15YBFwnsVorDFG/u0cVVQN5G2a3V8zv5/N6KN3TCG+ajKtaALcy7u14DCSrJI+gZeyYquFL9cioJXOGXSvg==";
      };
    };
    "unified-message-control-1.0.4" = {
      name = "unified-message-control";
      packageName = "unified-message-control";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/unified-message-control/-/unified-message-control-1.0.4.tgz";
        sha512 = "e1dEtN4Z/TvLn/qHm+xeZpzqhJTtfZusFErk336kkZVpqrJYiV9ptxq+SbRPFMlN0OkjDYHmVJ929KYjsMTo3g==";
      };
    };
    "unist-util-generated-1.1.6" = {
      name = "unist-util-generated";
      packageName = "unist-util-generated";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-generated/-/unist-util-generated-1.1.6.tgz";
        sha512 = "cln2Mm1/CZzN5ttGK7vkoGw+RZ8VcUH6BtGbq98DDtRGquAAOXig1mrBQYelOwMXYS8rK+vZDyyojSjp7JX+Lg==";
      };
    };
    "unist-util-is-3.0.0" = {
      name = "unist-util-is";
      packageName = "unist-util-is";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-is/-/unist-util-is-3.0.0.tgz";
        sha512 = "sVZZX3+kspVNmLWBPAB6r+7D9ZgAFPNWm66f7YNb420RlQSbn+n8rG8dGZSkrER7ZIXGQYNm5pqC3v3HopH24A==";
      };
    };
    "unist-util-modify-children-2.0.0" = {
      name = "unist-util-modify-children";
      packageName = "unist-util-modify-children";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-modify-children/-/unist-util-modify-children-2.0.0.tgz";
        sha512 = "HGrj7JQo9DwZt8XFsX8UD4gGqOsIlCih9opG6Y+N11XqkBGKzHo8cvDi+MfQQgiZ7zXRUiQREYHhjOBHERTMdg==";
      };
    };
    "unist-util-position-3.1.0" = {
      name = "unist-util-position";
      packageName = "unist-util-position";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-position/-/unist-util-position-3.1.0.tgz";
        sha512 = "w+PkwCbYSFw8vpgWD0v7zRCl1FpY3fjDSQ3/N/wNd9Ffa4gPi8+4keqt99N3XW6F99t/mUzp2xAhNmfKWp95QA==";
      };
    };
    "unist-util-remove-position-1.1.4" = {
      name = "unist-util-remove-position";
      packageName = "unist-util-remove-position";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-remove-position/-/unist-util-remove-position-1.1.4.tgz";
        sha512 = "tLqd653ArxJIPnKII6LMZwH+mb5q+n/GtXQZo6S6csPRs5zB0u79Yw8ouR3wTw8wxvdJFhpP6Y7jorWdCgLO0A==";
      };
    };
    "unist-util-stringify-position-1.1.2" = {
      name = "unist-util-stringify-position";
      packageName = "unist-util-stringify-position";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-stringify-position/-/unist-util-stringify-position-1.1.2.tgz";
        sha512 = "pNCVrk64LZv1kElr0N1wPiHEUoXNVFERp+mlTg/s9R5Lwg87f9bM/3sQB99w+N9D/qnM9ar3+AKDBwo/gm/iQQ==";
      };
    };
    "unist-util-stringify-position-2.0.3" = {
      name = "unist-util-stringify-position";
      packageName = "unist-util-stringify-position";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-stringify-position/-/unist-util-stringify-position-2.0.3.tgz";
        sha512 = "3faScn5I+hy9VleOq/qNbAd6pAx7iH5jYBMS9I1HgQVijz/4mv5Bvw5iw1sC/90CODiKo81G/ps8AJrISn687g==";
      };
    };
    "unist-util-stringify-position-3.0.0" = {
      name = "unist-util-stringify-position";
      packageName = "unist-util-stringify-position";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-stringify-position/-/unist-util-stringify-position-3.0.0.tgz";
        sha512 = "SdfAl8fsDclywZpfMDTVDxA2V7LjtRDTOFd44wUJamgl6OlVngsqWjxvermMYf60elWHbxhuRCZml7AnuXCaSA==";
      };
    };
    "unist-util-visit-1.4.1" = {
      name = "unist-util-visit";
      packageName = "unist-util-visit";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-visit/-/unist-util-visit-1.4.1.tgz";
        sha512 = "AvGNk7Bb//EmJZyhtRUnNMEpId/AZ5Ph/KUpTI09WHQuDZHKovQ1oEv3mfmKpWKtoMzyMC4GLBm1Zy5k12fjIw==";
      };
    };
    "unist-util-visit-children-1.1.4" = {
      name = "unist-util-visit-children";
      packageName = "unist-util-visit-children";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-visit-children/-/unist-util-visit-children-1.1.4.tgz";
        sha512 = "sA/nXwYRCQVRwZU2/tQWUqJ9JSFM1X3x7JIOsIgSzrFHcfVt6NkzDtKzyxg2cZWkCwGF9CO8x4QNZRJRMK8FeQ==";
      };
    };
    "unist-util-visit-parents-2.1.2" = {
      name = "unist-util-visit-parents";
      packageName = "unist-util-visit-parents";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-visit-parents/-/unist-util-visit-parents-2.1.2.tgz";
        sha512 = "DyN5vD4NE3aSeB+PXYNKxzGsfocxp6asDc2XXE3b0ekO2BaRUpBicbbUygfSvYfUz1IkmjFR1YF7dPklraMZ2g==";
      };
    };
    "vfile-3.0.1" = {
      name = "vfile";
      packageName = "vfile";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile/-/vfile-3.0.1.tgz";
        sha512 = "y7Y3gH9BsUSdD4KzHsuMaCzRjglXN0W2EcMf0gpvu6+SbsGhMje7xDc8AEoeXy6mIwCKMI6BkjMsRjzQbhMEjQ==";
      };
    };
    "vfile-location-2.0.6" = {
      name = "vfile-location";
      packageName = "vfile-location";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile-location/-/vfile-location-2.0.6.tgz";
        sha512 = "sSFdyCP3G6Ka0CEmN83A2YCMKIieHx0EDaj5IDP4g1pa5ZJ4FJDvpO0WODLxo4LUX4oe52gmSCK7Jw4SBghqxA==";
      };
    };
    "vfile-message-1.1.1" = {
      name = "vfile-message";
      packageName = "vfile-message";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile-message/-/vfile-message-1.1.1.tgz";
        sha512 = "1WmsopSGhWt5laNir+633LszXvZ+Z/lxveBf6yhGsqnQIhlhzooZae7zV6YVM1Sdkw68dtAW3ow0pOdPANugvA==";
      };
    };
    "vfile-message-3.0.1" = {
      name = "vfile-message";
      packageName = "vfile-message";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile-message/-/vfile-message-3.0.1.tgz";
        sha512 = "gYmSHcZZUEtYpTmaWaFJwsuUD70/rTY4v09COp8TGtOkix6gGxb/a8iTQByIY9ciTk9GwAwIXd/J9OPfM4Bvaw==";
      };
    };
    "vscode-jsonrpc-4.0.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-4.0.0.tgz";
        sha512 = "perEnXQdQOJMTDFNv+UF3h1Y0z4iSiaN9jIlb0OqIYgosPCZGYh/MCUlkFtV2668PL69lRDO32hmvL2yiidUYg==";
      };
    };
    "vscode-languageserver-5.2.1" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-5.2.1.tgz";
        sha512 = "GuayqdKZqAwwaCUjDvMTAVRPJOp/SLON3mJ07eGsx/Iq9HjRymhKWztX41rISqDKhHVVyFM+IywICyZDla6U3A==";
      };
    };
    "vscode-languageserver-protocol-3.14.1" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.14.1.tgz";
        sha512 = "IL66BLb2g20uIKog5Y2dQ0IiigW0XKrvmWiOvc0yXw80z3tMEzEnHjaGAb3ENuU7MnQqgnYJ1Cl2l9RvNgDi4g==";
      };
    };
    "vscode-languageserver-types-3.14.0" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.14.0.tgz";
        sha512 = "lTmS6AlAlMHOvPQemVwo3CezxBp0sNB95KNPkqp3Nxd5VFEnuG1ByM0zlRWos0zjO3ZWtkvhal0COgiV1xIA4A==";
      };
    };
    "vscode-uri-1.0.8" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-1.0.8.tgz";
        sha512 = "obtSWTlbJ+a+TFRYGaUumtVwb+InIUVI0Lu0VBUAPmj2cU5JutEXg3xUE0c2J5Tcy7h2DEKVJBFi+Y9ZSFzzPQ==";
      };
    };
    "wrapped-1.0.1" = {
      name = "wrapped";
      packageName = "wrapped";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrapped/-/wrapped-1.0.1.tgz";
        sha1 = "c783d9d807b273e9b01e851680a938c87c907242";
      };
    };
    "x-is-string-0.1.0" = {
      name = "x-is-string";
      packageName = "x-is-string";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/x-is-string/-/x-is-string-0.1.0.tgz";
        sha1 = "474b50865af3a49a9c4657f05acd145458f77d82";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
  };
in
{
  unified-language-server = nodeEnv.buildNodePackage {
    name = "unified-language-server";
    packageName = "unified-language-server";
    version = "0.3.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/unified-language-server/-/unified-language-server-0.3.0.tgz";
      sha512 = "N+ENrder8z9zJQF9UM7K3/1LcfVW60omqeyaQsu6GN1BGdCgPm8gdHssn7WRD7vx+ABKc82IE1+pJyHOPkwe+w==";
    };
    dependencies = [
      sources."@types/node-15.0.2"
      sources."@types/unist-2.0.3"
      sources."@types/vfile-3.0.2"
      sources."@types/vfile-message-2.0.0"
      sources."array-iterate-1.1.4"
      sources."bail-1.0.5"
      sources."character-entities-1.2.4"
      sources."character-entities-legacy-1.1.4"
      sources."character-reference-invalid-1.1.4"
      sources."co-3.1.0"
      sources."collapse-white-space-1.0.6"
      sources."dictionary-en-gb-2.3.0"
      sources."extend-3.0.2"
      sources."inherits-2.0.4"
      sources."irregular-plurals-2.0.0"
      sources."is-alphabetical-1.0.4"
      sources."is-alphanumerical-1.0.4"
      sources."is-buffer-2.0.5"
      sources."is-decimal-1.0.4"
      sources."is-hexadecimal-1.0.4"
      sources."is-plain-obj-1.1.0"
      sources."is-whitespace-character-1.0.4"
      sources."is-word-character-1.0.4"
      sources."lodash.includes-4.3.0"
      sources."markdown-escapes-1.0.4"
      sources."mdast-comment-marker-1.1.2"
      sources."mdast-util-heading-style-1.0.6"
      sources."mdast-util-to-nlcst-3.2.3"
      sources."mdast-util-to-string-1.1.0"
      sources."nlcst-is-literal-1.2.2"
      sources."nlcst-to-string-2.0.4"
      sources."nspell-2.1.5"
      sources."parse-english-4.2.0"
      sources."parse-entities-1.2.2"
      sources."parse-latin-4.3.0"
      sources."plur-3.1.1"
      sources."quotation-1.1.3"
      sources."remark-lint-6.0.6"
      sources."remark-lint-blockquote-indentation-1.0.4"
      sources."remark-lint-code-block-style-1.0.4"
      sources."remark-lint-definition-case-1.0.5"
      sources."remark-lint-definition-spacing-1.0.5"
      sources."remark-lint-emphasis-marker-1.0.4"
      sources."remark-lint-fenced-code-flag-1.0.4"
      sources."remark-lint-fenced-code-marker-1.0.4"
      sources."remark-lint-file-extension-1.0.5"
      sources."remark-lint-final-definition-1.0.4"
      sources."remark-lint-hard-break-spaces-1.0.5"
      sources."remark-lint-heading-increment-1.0.4"
      sources."remark-lint-heading-style-1.0.4"
      sources."remark-lint-link-title-style-1.0.5"
      sources."remark-lint-list-item-content-indent-1.0.4"
      sources."remark-lint-list-item-indent-1.0.5"
      sources."remark-lint-list-item-spacing-1.1.4"
      sources."remark-lint-maximum-heading-length-1.0.4"
      sources."remark-lint-maximum-line-length-1.2.2"
      sources."remark-lint-no-auto-link-without-protocol-1.0.4"
      sources."remark-lint-no-blockquote-without-marker-2.0.4"
      sources."remark-lint-no-consecutive-blank-lines-1.0.4"
      sources."remark-lint-no-duplicate-headings-1.0.5"
      sources."remark-lint-no-emphasis-as-heading-1.0.4"
      sources."remark-lint-no-file-name-articles-1.0.5"
      sources."remark-lint-no-file-name-consecutive-dashes-1.0.5"
      sources."remark-lint-no-file-name-irregular-characters-1.0.5"
      sources."remark-lint-no-file-name-mixed-case-1.0.5"
      sources."remark-lint-no-file-name-outer-dashes-1.0.6"
      sources."remark-lint-no-heading-punctuation-1.0.4"
      sources."remark-lint-no-inline-padding-1.0.5"
      sources."remark-lint-no-literal-urls-1.0.4"
      sources."remark-lint-no-multiple-toplevel-headings-1.0.5"
      sources."remark-lint-no-shell-dollars-1.0.4"
      sources."remark-lint-no-shortcut-reference-image-1.0.4"
      sources."remark-lint-no-shortcut-reference-link-1.0.5"
      sources."remark-lint-no-table-indentation-1.0.5"
      sources."remark-lint-ordered-list-marker-style-1.0.4"
      sources."remark-lint-ordered-list-marker-value-1.0.5"
      sources."remark-lint-rule-style-1.0.4"
      sources."remark-lint-strong-marker-1.0.4"
      sources."remark-lint-table-cell-padding-1.0.5"
      sources."remark-lint-table-pipe-alignment-1.0.4"
      sources."remark-lint-table-pipes-1.0.4"
      sources."remark-lint-unordered-list-marker-style-1.0.4"
      sources."remark-message-control-4.2.0"
      sources."remark-parse-6.0.3"
      sources."remark-preset-lint-markdown-style-guide-2.1.4"
      sources."remark-retext-3.1.3"
      sources."repeat-string-1.6.1"
      sources."replace-ext-1.0.0"
      sources."retext-6.0.2"
      sources."retext-english-3.0.4"
      sources."retext-latin-2.0.4"
      sources."retext-spell-2.4.1"
      sources."retext-stringify-2.0.4"
      sources."sliced-1.0.1"
      sources."state-toggle-1.0.3"
      sources."trim-0.0.1"
      sources."trim-trailing-lines-1.1.4"
      sources."trough-1.0.5"
      sources."unherit-1.1.3"
      sources."unified-7.1.0"
      sources."unified-lint-rule-1.0.6"
      sources."unified-message-control-1.0.4"
      sources."unist-util-generated-1.1.6"
      sources."unist-util-is-3.0.0"
      sources."unist-util-modify-children-2.0.0"
      sources."unist-util-position-3.1.0"
      sources."unist-util-remove-position-1.1.4"
      sources."unist-util-stringify-position-2.0.3"
      sources."unist-util-visit-1.4.1"
      sources."unist-util-visit-children-1.1.4"
      sources."unist-util-visit-parents-2.1.2"
      (sources."vfile-3.0.1" // {
        dependencies = [
          sources."unist-util-stringify-position-1.1.2"
          sources."vfile-message-1.1.1"
        ];
      })
      sources."vfile-location-2.0.6"
      (sources."vfile-message-3.0.1" // {
        dependencies = [
          sources."unist-util-stringify-position-3.0.0"
        ];
      })
      sources."vscode-jsonrpc-4.0.0"
      sources."vscode-languageserver-5.2.1"
      sources."vscode-languageserver-protocol-3.14.1"
      sources."vscode-languageserver-types-3.14.0"
      sources."vscode-uri-1.0.8"
      sources."wrapped-1.0.1"
      sources."x-is-string-0.1.0"
      sources."xtend-4.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A language server for spoken languages using retext";
      homepage = "https://github.com/aecepoglu/retext-language-server";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
