require("plugins.auto-save")
-- require 'plugins.barbar'
require("plugins.cmp")
require("plugins.dap")
require("plugins.dashboard")
require("plugins.diffview")
require("plugins.gitsigns")
require("plugins.indent-blankline")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.luasnip")
require("plugins.neogit")
require("plugins.neotest")
require("plugins.neoscroll")
-- require("plugins.nnn")
require("plugins.nvim-lint")
require("plugins.nvim-tree")
require("plugins.octo")
require("plugins.rest")
require("plugins.telescope")
require("plugins.trouble")
require("plugins.treesitter")
---require("plugins.ultest")
require("plugins.whichkey")
require("plugins.hop")
require("plugins.comment")

require("my.utils")
require("my.autocommands")
require("my.settings")
require("my.keymap")
